### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by ikishanoza** [Napster2210/ngx-spinner#100]
I have install the lastest version but I have use in ionic which is based on angular so I though it must get worked but I am having this issue when I run the project.
```
Uncaught TypeError: Object(...) is not a function
    at ngx-spinner.js:208
    at Object.<anonymous> (ngx-spinner.js:210)
    at __webpack_require__ (bootstrap 412c658a2792c464c88c:54)
    at Object.363 (main.ts:5)
    at __webpack_require__ (bootstrap 412c658a2792c464c88c:54)
    at Object.358 (main.ts:1)
    at __webpack_require__ (bootstrap 412c658a2792c464c88c:54)
    at webpackJsonpCallback (bootstrap 412c658a2792c464c88c:25)
    at main.js:1
```

here is my app module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { IonicStorageModule } from '@ionic/storage';
import { AuthProvider } from '../providers/auth/auth';
import { AngularFireModule } from '@angular/fire';
import { AngularFirestoreModule } from '@angular/fire/firestore';
import { AngularFireAuthModule } from '@angular/fire/auth';
import { environment } from '../environments/environment';
import { NgxSpinnerModule } from "ngx-spinner";
@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    NgxSpinnerModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule, // imports firebase/firestore, only needed for database features
    AngularFireAuthModule,
    IonicStorageModule.forRoot(),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    AuthProvider,
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ]
})
export class AppModule {}

```

and in home.ts I have used as a service like you describe in doc but i am not able to run this

can you please help ?

**Comment by Napster2210** [comment]
@Kishanlos007 Which version of angular and ngx-spinner you're using?

**Comment by macbird** [comment]
I have the same error, my angular's version is 7.0

**Comment by Napster2210** [comment]
@macbird if your Angular version is 7 then you've to use ngx-spinner 7.2.0

**Comment by macbird** [comment]
thanks, it worked perfectly!

**Comment by KishanIos007** [comment]
okay let me try this vesrion..

**Comment by KishanIos007** [comment]
Nope not working still the same error

**Comment by flowest** [comment]
@Napster2210 

> @macbird if your Angular version is 7 then you've to use ngx-spinner 7.2.0

this version still has the [name] issue mentioned here:
https://github.com/Napster2210/ngx-spinner/issues/84

**Comment by KishanIos007** [comment]
any updates @Napster2210

**Comment by sonalradical** [comment]
I am also getting same issue

**Comment by flowest** [comment]
@Napster2210 please help us to solve 😃

**Comment by AhmadHassanAwan** [comment]
> @macbird if your Angular version is 7 then you've to use ngx-spinner 7.2.0

Thanks, this worked..

**Comment by rspl-yuvraj** [comment]
@ikishanoza @flowest Can you please reproduce the issue by creating [stackblitz](https://stackblitz.com/fork/angular)

**Comment by flowest** [comment]
just created a stackblitz [here](https://stackblitz.com/edit/angular-xv7bvb) and noticed it works 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
noticed that i use version 7.1.4 in my project where the binding issue to naming exists...
i will update and check it on my side.

@rspl-yuvraj Thanks for bringing me to create a stackblitz! 😃

**Comment by rspl-yuvraj** [comment]
@flowest Thanx for creating Stackblitz, it will be helpful for others as well. I'm closing this issue. Feel free to create a new one if you face anything.
