### ISSUE TITLE
view Warning after install ngx-spinner

### ISSUE THREAD

**Issue by jogHar** [Napster2210/ngx-spinner#101]
WARNING in ./node_modules/ngx-spinner/fesm5/ngx-spinner.js
208:59-77 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

**Comment by lukesUbuntu** [comment]
Will be your Angular version you should install ngx-spinner@7.2.0
What version of Angular are you using?

**Comment by jogHar** [comment]
Thanks, @lukesUbuntu.

**Comment by Arthi93** [comment]
> Will be your Angular version you should install ngx-spinner@7.2.0
> What version of Angular are you using?

Wow, that solved my Issue. Git hub page should be corrected from ">= 7.2.0" to "= 7.2.0" for angular 7

**Comment by rspl-yuvraj** [comment]
@Arthi93 Thanx for pointing out I'll update it soon.
