### ISSUE TITLE
hi this is very useful, we need to load text pass the parameter like a NgxSpinnerService.show()

### ISSUE THREAD

**Issue by rajkumars22** [Napster2210/ngx-spinner#103]
`ngx-spinner` is a custom element, so in this case, if you add `<ngx-spinner>` in your HTML file then you have to add **CUSTOM_ELEMENTS_SCHEMA** to your app module.

```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

// ........

@NgModule({
// ...
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
]
})
```

**Comment by rspl-yuvraj** [comment]
@rajkumars22 Can you please explain your requirement in detail? If you want dynamic **Loading Text**, then it's totally up to you. You can set dynamic text by putting some logic in your component.

**Comment by rajkumars22** [comment]
Ya yes. Loading Text dynamically - putting some logic in my component

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rspl-yuvraj** [comment]
@rajkumars22 Let me know if I can help.

**Comment by rspl-yuvraj** [comment]
@rajkumars22 

1. Create one function in your component which handles your spinner's `show` method
2. Set one variable's value in the same function based on your requirement/condition
3. Then call `show` method of the spinner in the same function

```
loadingText: string = 'Loading...';

handleDynamicLoadingText = () => {
   if(condition === true) {  // replace with your condition
     this.loadingText = 'Pleaase wait...';
   }
   this.spinner.show();  // show spinner
}
```

**Comment by rajkumars22** [comment]
Ok thank you!. I will try and let you know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pavankjadda** [comment]
@rspl-yuvraj  Does this work? I just tried it using the following config and I don't see the text
```
   this.loadingText="Adding Event...";

    this.ngxSpinnerService.show(undefined,
      {
        type: 'ball-circus',
        size: 'medium',
        bdColor: 'rgba(51, 51, 51, 0.9)',
        color: 'white',
        fullScreen: true,
      }
    );

```

**Comment by rspl-yuvraj** [comment]
@pavankjadda You have to pass your `loadingText` variable in HTML this way:
```
<ngx-spinner>
<p style="font-size: 20px; color: white">{{loadingText}}</p>
</ngx-spinner>
```
