### ISSUE TITLE
Doesn't work if placed under ng-template

### ISSUE THREAD

**Issue by vatsalpande** [Napster2210/ngx-spinner#105]
I am trying to use this component under ng-template. As soon as I place it under ng-template it stops to work. If I move it out of it, it works.

https://stackblitz.com/edit/angular-mtbjhb?file=src/app/app.component.html

Is this by design? Is there any way to make it work with ng-template?

**Comment by rspl-yuvraj** [comment]
@vatsalpande 
This is normal and it's the expected behavior. This is because with the `ng-template` tag you are simply defining a template, but you are not using it yet.

```
<div *ngIf="someting else loading"></div>
<ng-template #loading>
  <ngx-spinner></ngx-spinner>
</ng-template>
```

**Comment by rspl-yuvraj** [comment]
Closing the issue.
