### ISSUE TITLE
multiple spinner

### ISSUE THREAD

**Issue by gischy** [Napster2210/ngx-spinner#112]
I could not use multiple spinner spread over different components inside one angular application. Controling a single spinner with name property does not work.

   "@angular/animations": "~8.1.1",
    "@angular/common": "~8.1.1",
    "@angular/compiler": "~8.1.1",
    "@angular/core": "~8.1.1",
    "@angular/forms": "~8.1.1",
    "@angular/platform-browser": "~8.1.1",
    "@angular/platform-browser-dynamic": "~8.1.1",
    "@angular/router": "~8.1.1",
    "ngx-spinner": "^8.0.3",

**Comment by rspl-yuvraj** [comment]
@gischy Can you please share your example code using [Stackblitz](https://stackblitz.com/) ?

**Comment by gischy** [comment]
https://stackblitz.com/edit/angular-25xpwc

in this stackblitz when the app is initalized i want 3 spinner to be displayed (each component comp1, comp2, comp3 has a spinner which should be displayed when the component is initalized...)
`  ngOnInit() {
    // somehow only spinner 3 of comp3 is displayed when the app is initalized
    this.spinner.show("sp3");
    setTimeout(()=>{
      this.spinner.hide("sp3")
      }, 5000);

  }`

**Comment by rspl-yuvraj** [comment]
@gischy This happens due to the quick execution of each `show` function of the spinner, it won't wait for the previous spinner instance to execute. So do one thing just wrapped your `show` method in `setTimeout` with 0(zero) ms.

```
setTimeout(() => {
      this.spinner.show("sp1");  // sp1, sp2, sp3
}, 0);
```

Let me know if you still face the same issue.

**Comment by gischy** [comment]
wrapping the show call inside that the setTimeout() method works, thank you

**Comment by gischy** [comment]
until that could be fixed, there should be some hints inside the readme

**Comment by rspl-yuvraj** [comment]
@gischy I'll add that in my next release. Thanx.
