### ISSUE TITLE
Multiple spinner not working

### ISSUE THREAD

**Issue by Mathieu-DUSSART** [Napster2210/ngx-spinner#113]
Hi,
When I show two spinners at the same time, only one is showing.

Example : 
It's working when the spinners are not showed at the same time (the spinner in the red div shows after 2sec) : https://stackblitz.com/edit/angular-qqp7t9

But it's not working when showed at the same time : https://stackblitz.com/edit/angular-ppnywm

**Comment by rspl-yuvraj** [comment]
Duplicated by #112 , @Mathieu-DUSSART please check the issue #112 for the solution.
