### ISSUE TITLE
Spinner opacity doesn't take up the passed value and always uses 1

### ISSUE THREAD

**Issue by kshkrao3** [Napster2210/ngx-spinner#114]
The spinner opacity is not taking up the value and is always set to 1. I am using v8.1.0 and the same can be seen in the demo site - https://napster2210.github.io/ngx-spinner/

Also, I noticed that there is not `@Input` property for `bdOpacity`. Was this removed anytime?

Could you please check this and let us know?

**Comment by Napster2210** [comment]
@kshkrao3 It was removed earlier in **v2.0.0** : https://github.com/Napster2210/ngx-spinner/releases/tag/v2.0.0

You've to use background colour in `RGBA` format where alpha value is used for opacity. The website is not the updated one, I'm working on new website. But you can get help of README file.

**Comment by kshkrao3** [comment]
Ah, I see. Thanks for the response and update.. :)
