### ISSUE TITLE
Spinner causes memory leak

### ISSUE THREAD

**Issue by Arthi93** [Napster2210/ngx-spinner#115]
After adding ngx-spinner to my app, memory leaks appears preventing the component from being released and causing massive memory allocation. After commenting spinner, memory management works perfectly. Jumping between two identical components - one with spinner, one without, i saw growing delta in chrome dev tools. Is there any way to manually release spinner subscriptions/resources on component destroy?

**Comment by Napster2210** [comment]
@Arthi93 Which version of `ngx-spinner` you're using?

**Comment by rspl-yuvraj** [comment]
Duplicated by #111

**Comment by Napster2210** [comment]
@Arthi93 Closing the issue due to inactivity, feel free to re-open if you're still facing the same issue.
