### ISSUE TITLE
Change CSS of ngx-spinner 

### ISSUE THREAD

**Issue by abdes-zakari** [Napster2210/ngx-spinner#118]
There is any way to change `position:"absolute"` to `"relative"` of the spinner?

and how i can remove the black overlay from spinner?

**Comment by Napster2210** [comment]
@abdes-zakari you can set `bgColor` it's a RGBA value so just set 0 as alpha value

**Comment by abdes-zakari** [comment]
Thanks for your reply but how i can change the position from absolute to relative.

![baaaan](https://user-images.githubusercontent.com/30769602/72590558-5230cd00-38fe-11ea-8a0e-009797ae752c.PNG)

**Comment by rspl-yuvraj** [comment]
@abdes-zakari No need to change `position`

**Comment by rspl-yuvraj** [comment]
`<ngx-spinner bdColor='transparent'></ngx-spinner>` You can set like this. @abdes-zakari Let me know if you want something else.

**Comment by rspl-yuvraj** [comment]
There is no way to change the `position` from `absolute` to `relative`.
