### ISSUE TITLE
After hiding the spinner and calling `show` method it does not work.

### ISSUE THREAD

**Issue by monis001** [Napster2210/ngx-spinner#119]
Hi, 

first of all awesome library with minimal setup, really helpful. I want to call spinner whenever API is called, sp apparently I added the service inside interceptor and called `show()`  and `hide()` accordingly. It works perfectly for the first case when the next API is called and when it calls `show()` method spinner does not work.

After hiding the spinner and calling back again it's not working. I am missing some other configuration??

Any help will be appreciated.
Thanks
P.S.: I have not shared any code snippet because the straight forward implementation for spinner  is working fine.

**Comment by rspl-yuvraj** [comment]
@monis001 Check this out: https://stackblitz.com/edit/angular-e7djzt
You can make the necessary changes and revert back to me.
