### ISSUE TITLE
Increase divCount in spinner.divArray

### ISSUE THREAD

**Issue by vedankita** [Napster2210/ngx-spinner#120]
how to increase divCount in spinner.divArray. Default value is 3 but I want 5 balls loader, in this case how to change it. I am using ball-pulse type. I am using angular 7 so I can't do changes in main js file. Is there any attribute to increase divcount

**Comment by Napster2210** [comment]
@vedankita You can not change `divCount`. Every divCount has separate type of spinner allocated.

**Comment by Napster2210** [comment]
@vedankita You can use `ball-pulse-rise` which has 5 balls.

**Comment by vedankita** [comment]
But it's animation is different. I want animation like progress bar

**Comment by Napster2210** [comment]
It's a more CSS related change, but for that, you've to change core library. You can fork my work and made necessary changes as per your requirements.

**Comment by vedankita** [comment]
Thanks @Napster2210. I have changed animation for this effect.
