### ISSUE TITLE
Update to Angular 9

### ISSUE THREAD

**Issue by PooSham** [Napster2210/ngx-spinner#121]
Angular 9 is out, please update peerDependencies

**Comment by Napster2210** [comment]
@PooSham Thanx, in my plan.

**Comment by SenAlexandru** [comment]
@Napster2210 - Is there an approximate date on when will the angular9 compatible version will be out? Thank you very much!

**Comment by Napster2210** [comment]
@SenAlexandru in next week, maybe before 28th February.

**Comment by azche** [comment]
...any update on this? thanks!

**Comment by rspl-yuvraj** [comment]
@azche Working on the same will release in the next 2 days.

**Comment by Napster2210** [comment]
@PooSham @SenAlexandru @azche Latest version is published [v9](https://github.com/Napster2210/ngx-spinner/releases/tag/v9.0)

**Comment by reinaldorauch** [comment]
Installed about now and npm reported this to me:

![image](https://user-images.githubusercontent.com/2676370/76259880-5a89f200-6235-11ea-8a4d-c113b9241130.png)

**Comment by reinaldorauch** [comment]
I've open a pull request that fixes it #124
