### ISSUE TITLE
Feature Request: Show with timeout

### ISSUE THREAD

**Issue by davidfindlay** [Napster2210/ngx-spinner#123]
If something else goes wrong with an application while the spinner is showing it'll show immediately. I'd like to have a timeout callback available so I can have it report an error to my logs and the user if the spinner spins for too long.

**Comment by ShiftyMcCool** [comment]
i do this with finalize() on all my subscriptions.  if your route throws an error, run your callback.

**Comment by rspl-yuvraj** [comment]
@davidfindlay As @ShiftyMcCool mentioned, you can do this at your end. As of now, not such kind of functionality in future plans.
