### ISSUE TITLE
Hide Method not working in sync

### ISSUE THREAD

**Issue by asahu132** [Napster2210/ngx-spinner#126]
If i write the below code, Loader should  be visible all the time because just after hiding the loader i am showing it again, but here hide method is not working in sync. 
show method is showing the loader again before hide method work is done.
```
this.spinner.show();
setTimeout(() => {
      /** spinner ends after 5 seconds */
      this.spinner.hide();
      this.spinner.show();
    }, 5000);
```

Version - 9.0.1
Browser - chrome

**Comment by rspl-yuvraj** [comment]
@asahu132 Try below code:
```
this.spinner.show();
setTimeout(async() => {
      /** spinner ends after 5 seconds */
      await this.spinner.hide();
      this.spinner.show();
    }, 5000);
```
