### ISSUE TITLE
Broken animation on pacman without fullscreen

### ISSUE THREAD

**Issue by wittlock** [Napster2210/ngx-spinner#127]
Was just playing around a bit on the demo page and found a broken animation. Running the demo as is but changing spinner type to pacman and disabling fullscreen appears to break the animation. Tested on Chrome v80 and v81.

```<ngx-spinner bdColor = "rgba(0, 0, 0, 0.8)" size = "medium" color = "#fff" type = "pacman" [fullScreen] = "false"><p style="color: white" > Loading... </p></ngx-spinner>```

Haven't tried it locally but cannot see any relevant commits since 9.0.1 that the demo page appears to run, so I'm guessing it's broken even in latest.

**Comment by rspl-yuvraj** [comment]
@wittlock Thanx for raising the issue. I'll take a look and fix it soon.

**Comment by Napster2210** [comment]
This is resolved and will be available in next release.

**Comment by Napster2210** [comment]
Latest version `v10.0.0` is released!!!!!
https://github.com/Napster2210/ngx-spinner/releases/tag/v10.0.0
