### ISSUE TITLE
ngx-spinner inside dialog

### ISSUE THREAD

**Issue by heshamz** [Napster2210/ngx-spinner#128]
Hi,
I am trying to put the spinner inside a dialog and started once the dialog opened, but I receive "expression has changed after it was checked" error. I tried with mat-dialog (angular material) and nb-dialog (Nebular) but with the same result.

Do you have any sample on how to add the spinner inside the dialog and started on dialog open.

Thanks

**Comment by rspl-yuvraj** [comment]
@heshamz When you're hiding spinner?

**Comment by heshamz** [comment]
@rspl-yuvraj on the dialog
I have a dialog and inside the dialog, there is a data grid on the beginning of data load I show the spinner and on data load ended I hide it.
The data grid sends a message on the start of load and the finish.

**Comment by rspl-yuvraj** [comment]
@heshamz That's the issue with the Angular framework itself. This happens when your variable value is changed within a fraction of second. You can avoid this type of error by wrapping spinner methods into `setTimeout` method.
