### ISSUE TITLE
Not able to load customised image

### ISSUE THREAD

**Issue by benedict1986** [Napster2210/ngx-spinner#129]
Hi, thank you for developing this useful library. I have an issue of using my own image. I tried that in one of your example, https://stackblitz.com/edit/angular-exgxk2?file=src%2Fapp%2Fapp.component.html

What I changed is

1). Add name to ngx-spinner as

```
<ngx-spinner name='abc'>
    <p class="loading">Loading Awesomeness...</p>
</ngx-spinner>
```

2. Add template to show function

```
this.spinner.show("abc",
{
      bdColor: "rgba(0, 0, 0, 1)",
      template: "<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/768px-Flat_tick_icon.svg.png' />"
});
```

However, when I click `Change Options` button, it loads la-ball-scale-multiple, instead of the png image.

BTW, if I add template attribute in ngx-spinner html tag, it works fine

Can you please help?

Thank you

**Comment by kostenickj** [comment]
same issue here.

**Comment by rspl-yuvraj** [comment]
@benedict1986 @kostenickj Thanx for pointing out. I'll take care of it.

**Comment by Napster2210** [comment]
@benedict1986 @kostenickj There is a limitation by Angular itself. You can check this out: https://github.com/angular/angular/issues/23916

If you find anything for the same let me know or raise a PR for that. Thanx.
