### ISSUE TITLE
show the spinner from the template

### ISSUE THREAD

**Issue by eng-dibo** [Napster2210/ngx-spinner#130]
add a template property to show the spinner, instead of using methods

```
<ngx-spinner show="loading"></ngx-spinner>
```
in `ts` file:
```
this.loading=true
```

**Comment by rspl-yuvraj** [comment]
@eng-dibo I'll keep in mind.

**Comment by izabekz** [comment]
@rspl-yuvraj Hi! Is there any progress on this issue? Just asking

**Comment by izabekz** [comment]
It would be very nice with this enhancement

**Comment by Napster2210** [comment]
@izabekz Not yet, I am planning new release for v11. I will include this in my list along with other features.

**Comment by izabekz** [comment]
@Napster2210 is there any date for new release that you are planning?

**Comment by Napster2210** [comment]
I am planning new release by end of this week. Most probably in weekends.

**Comment by Napster2210** [comment]
@izabekz I will try as early as possible.

**Comment by izabekz** [comment]
@Napster2210 Hi, is there any info on when the new release coming? Thanks

**Comment by Napster2210** [comment]
It's done and available in [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)
