### ISSUE TITLE
[error] ngx-spinner stops working after error occurs

### ISSUE THREAD

**Issue by ManCodeB** [Napster2210/ngx-spinner#131]
Hi guys,

I am using ngx-spinner v9.0.2 with Angular v9.1.4 and am experiencing the following issue.
Everything works fine and my spinner shows up whenever I want it to, but as soon as an application error happens (does not matter what kind of error) it won't show up anymore.

The rest of my application continues to work fine, except for the spinner. I have to refresh the page then it will show up again. As mentioned, this happens every time any subscription resolves the reject() callback.

I used to call this.spinner.show() on async actions before the subscription and no matter what am calling this.spinner.hide() in the resolve() and reject() callbacks. The spinner is hiding intentionally (so execution reaches that part of my code), but as mentioned won't ever show up again until I refresh my page.

Can anyone confirm this behaviour?

sidenote: I use ngx-spinner since two years (with Angular 7) and had never had any problems with it. But since the update to Angular 9 I am facing this issues.

**Comment by rspl-yuvraj** [comment]
@ManCodeB I'll check that.

**Comment by Napster2210** [comment]
Latest version `v10.0.0` is released!!!!!
https://github.com/Napster2210/ngx-spinner/releases/tag/v10.0.0

**Comment by Napster2210** [comment]
@ManCodeB Can you please check the issue is still reproducible in the latest version as well?

**Comment by Napster2210** [comment]
Closed due to inactivity, please free to raise another one if you faced something like this.
