### ISSUE TITLE
WARNING: sanitizing HTML stripped some content

### ISSUE THREAD

**Issue by peter-stoyanov** [Napster2210/ngx-spinner#132]
I get the following warning in the console logged each time the spinner with [template] option provided in the html is used:

**WARNING: sanitizing HTML stripped some content, see http://g.co/ng/security#xss**

Stackblitz to reproduce the issue, just open the console and click on 'Start Spinner'
[link to reproduce](https://stackblitz.com/edit/spinner-template-sanitize)

**Comment by rspl-yuvraj** [comment]
@Napster2210 will take care of this warning in the next version.

**Comment by Napster2210** [comment]
This is resolved and will be available in next version soon.

**Comment by Napster2210** [comment]
Latest version `v10.0.0` is released!!!!!
https://github.com/Napster2210/ngx-spinner/releases/tag/v10.0.0
