### ISSUE TITLE
Update to Angular 10

### ISSUE THREAD

**Issue by pavankjadda** [Napster2210/ngx-spinner#135]
Angular 10 is out, please update dependencies

**Comment by rspl-yuvraj** [comment]
I'll release a new version soon.

**Comment by FredyValstrauss** [comment]
I'm also looking for this. Thank you.

**Comment by devpurohit** [comment]
Please update soon. And if possible can someone give instruction on how we can upgrade it and make a pr. Would love to contribute!

**Comment by rspl-yuvraj** [comment]
@pavankjadda @rspl-yuvraj @FredyValstrauss @devpurohit New version will be there in this weekend itself with some fixes.

**Comment by Napster2210** [comment]
This is done will be releasing new version soon.

**Comment by Napster2210** [comment]
Latest version `v10.0.0` is released!!!!!
https://github.com/Napster2210/ngx-spinner/releases/tag/v10.0.0
