### ISSUE TITLE
Loading icon and text not displaying correctly during initial load in Firefox

### ISSUE THREAD

**Issue by pavankjadda** [Napster2210/ngx-spinner#137]
Loading icon and text not displaying correctly during initial load in Firefox(kind of freezes). I can reproduce the issue at demo site https://napster2210.github.io/ngx-spinner/

**Comment by xinthose** [comment]
Start spinner works fine for me in Firefox (77.0.1).

**Comment by pavankjadda** [comment]
@xinthose Doesn't it stutter during initial load?

**Comment by xinthose** [comment]
@pavankjadda I would have to see a video of your screen, but no, it looks fine for me.

**Comment by Napster2210** [comment]
![image](https://user-images.githubusercontent.com/17761063/87251093-c5b72f80-c486-11ea-803d-88f0dcde2ba4.png)

I have checked in Firefox and it's working perfectly fine for me. It maybe something else not with the spinner.

**Comment by pavankjadda** [comment]
Sorry for the late reply, here is the video of showing the stutter

https://imgur.com/a/WtsVZhJ

**Comment by pavankjadda** [comment]
I use Firefox 81.x now

**Comment by pavankjadda** [comment]
Okay, here is the issue. I see this stutter only when connected to 4K monitor and when disconnected the monitor it works fine. I filed a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1666911) with Firefox, let's wait and see if this is the issue
