### ISSUE TITLE
Configurable z-index of the black-overlay

### ISSUE THREAD

**Issue by ashankasr** [Napster2210/ngx-spinner#14]
Is it possible to expose the  `z-index` css property for configuration in `ngx-spinner` ?

**Comment by Napster2210** [comment]
@ashankasr Why do you want `z-index` to expose? Let me know if I can help you another way.

**Comment by ashankasr** [comment]
I have a status bar in the bottom of the screen which maintains what's happening in the background while the black-overlay on top of it. Problem is black-overlay distracting the content of the status bar. So I want black-overlay to have a lower z-index than the status bar.

**Comment by ashankasr** [comment]
Anyways I was able to configure my status bar z-index to more than black-overlay z-index which is actually fixing my issue. But I would like to see black-overlay to have a configurable z-index might be very usualful for other scenario.
