### ISSUE TITLE
RGB color attributes vs styling with CSS classes

### ISSUE THREAD

**Issue by yannpiot** [Napster2210/ngx-spinner#142]
Introducing a CSS class for the styling of a spinner would be more convenient than using the current [color] attribute. For instance, it would allow further customization beside the color (e.g. add a shadow if we wanted to) but also dynamic theming variables (achieved using, say, SCSS variables).

.spinnerstyle {
    background-color:$primary-color
    //etc.
}

I suppose the class could be either added as an attribute...

<ngx-spinner type="ball-clip-rotate" [fullScreen]="false" class="spinnerstyle" bdColor="rgba(255,255,255,0.90)">
</ngx-spinner>

or simply expose a class name and then the user to customise?

**Comment by InYourHead** [comment]
I found this issue and I found a workaround for it:

```
<ngx-spinner 
 [color]="'var(--spinner-color)'"
 [bdColor]="'var(--spinner-bd-color)'"
 ></ngx-spinner>
```

And define css variables like this:

```

:root {
 --spinner-color: red;
 --spinner-bd-color: white;
}
```
