### ISSUE TITLE
Bad dependencies

### ISSUE THREAD

**Issue by ANahr** [Napster2210/ngx-spinner#143]
The package for ngx-spinner 10 has the following peer dependencies:
  "peerDependencies": {
    "@angular/common": "^7.2.0",
    "@angular/core": "^7.2.0"
  },

These dependencies should refer to the correct angular 10 version packages instead.

**Comment by Napster2210** [comment]
@ANahr do you get any error?

**Comment by Napster2210** [comment]
This was intentionally, let me know if you're faced any issue with that.

**Comment by ANahr** [comment]
You get warnings

npm WARN ngx-spinner@10.0.0 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@10.0.0 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.

You should be able to build without warnings

**Comment by ANahr** [comment]
An an "ng update" will fail because of these dependencies

**Comment by Napster2210** [comment]
Ahh I see. Okay I'll change that and release the new version today itself.

**Comment by Napster2210** [comment]
Thanx for pointing out @ANahr

**Comment by Napster2210** [comment]
@ANahr @vltansky @pavankjadda This is done, you can find the updated version `v10.0.1` on [npm](https://www.npmjs.com/package/ngx-spinner)
