### ISSUE TITLE
Custom template for the spinner

### ISSUE THREAD

**Issue by jeevasusej** [Napster2210/ngx-spinner#144]
How to add custom template for the spinner instead of the default one?

**Comment by rspl-yuvraj** [comment]
@jeevasusej You follow the steps from README
https://github.com/Napster2210/ngx-spinner#using-custom-spinner

**Comment by jeevasusej** [comment]
In documentation, it uses images. 
Can we use template reference variable? 
I have tried but i didn't get it. Instead of the default spinner, If I want to load any different spinner how to achieve it?

**Comment by rspl-yuvraj** [comment]
@jeevasusej Can you post your HTML code snippet over here so I can help you with that.

**Comment by Napster2210** [comment]
@jeevasusej You can check this example: https://stackblitz.com/edit/angular-qb6k4h
I've created custom HTML template example for your reference. Hope this will help you.

**Comment by jeevasusej** [comment]
Please check the link. 
I don't know how to use it. Please consider the following demo. 

https://stackblitz.com/edit/angular-qkate4?file=src%2Fapp%2Fapp.component.html

**Comment by Napster2210** [comment]
@jeevasusej You can't directly pass template ref variable because allowable type is HTML only. So you've to pass HTML into the `template` input property as I did in above example. That is the limitation of library.

**Comment by jeevasusej** [comment]
It would be good if we add a label as enhancement
