### ISSUE TITLE
Position of loading text

### ISSUE THREAD

**Issue by ChrisWB** [Napster2210/ngx-spinner#145]
My problem goes in the same direction as described [here](https://github.com/Napster2210/ngx-spinner/issues/61), but I have no clue how to solve my problem.

We work with the attribute fullScreen = false and have parents with a fairly large height and also with a relatively low height. With these, the spinner text lies above the spinner animation.

To fix this, I would like to set the value for "top" to 50% for the class .loading-text. Then again using the attribute margin-block-start to an absolute value for the p-element of the loading text. Just to define a fixed space between the spinner graphic and the spinner text no matter the height of the parent.

Using :: ng-deep in my styles.scss I was unable to set the value. Does someone please have a hint for me?

**Comment by rspl-yuvraj** [comment]
Can you please create a [Stackblitz](https://stackblitz.com/fork/angular-ivy) to replicate the same issue?

**Comment by uler3161** [comment]
I had a similar issue For me, a short parent and it'd cause the text to render over the animation. I was able to get it the way I wanted with this:

```
::ng-deep .ngx-spinner-overlay {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

::ng-deep .ngx-spinner-overlay > div:first-child {
  all: unset !important;
}

::ng-deep .loading-text {
  all: unset !important;
  flex-grow: 0;
}
```
