### ISSUE TITLE
Spinner not showing

### ISSUE THREAD

**Issue by chhinendu** [Napster2210/ngx-spinner#146]
The issue is replicable when navigated using `this.router.navigate(['/documents']);` and then loader shown in the component init. This happens on page refresh as well. 

`this.spinner.show(); | spinner: NgxSpinnerService`

This is working fine on v8.0.3, in one of my live applications. 

Dev application is on Angular 9 and ngx-spinner-v9.0.2, and I see this issue. To confirm I used v8.0.3 on my Dev application and it works fine of both routing and reload.

**Comment by rspl-yuvraj** [comment]
@chhinendu Can you please create a [Stackblitz](https://stackblitz.com/fork/angular-ivy) to replicate the same issue?

**Comment by chhinendu** [comment]
While enable ivy, I was not able to get the application to start, however turning ivy off, the application works file. I have used same kind of code in my application. I had debugged my code, `.show()` is being called, but the spinner is not shown.I will try again to replicate.

https://stackblitz.com/edit/angular-ivy-rne86z

**Comment by Napster2210** [comment]
@chhinendu It's working for me on the above given URL: https://stackblitz.com/edit/angular-ivy-rne86z

**Comment by danieldanielecki** [comment]
It's also working for me on `Angular 10`, however it breaks on `Angular Universal`.

**Comment by Napster2210** [comment]
Latest version is available for Angular [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)

**Comment by ermanojsingh99** [comment]
i have angular 11 version ngx-spinner not showing .....i have already import

**Comment by Napster2210** [comment]
@ermanojsingh99 New version v12 is released, please check in latest version. If you guys still faced the issue(Except Angular Universal) then please reopen the issue with sample code.

**Comment by HamzaPY** [comment]
Spinner is not showing with Angular 12 and ngx-spinner version 12. 
Please help!

**Comment by Napster2210** [comment]
@HamzaPY Can you please post your block code on Stackblitz?

**Comment by HamzaPY** [comment]
It is same as the provided demo.

**Comment by spp125** [comment]
@Napster2210 Hi. I am using angular version #12.2.4 and Ngx spinner version # 12.0.0 but I am getting "ngxspinnermodule is not an angular module" error. I have import in app module as well in feature modules. Any input on fixing this issue?

**Comment by aostoic** [comment]
mismo problema angular 13
