### ISSUE TITLE
Concurrent spinners (fullScreen + non-fullScreen)

### ISSUE THREAD

**Issue by hhermas** [Napster2210/ngx-spinner#147]
I played with the multiple spinner demo and converted one of the spinners to be fullscreen.
Looks like it is possible to have a fullscreen and non-fullscreen spinner active at the same time.
But I'm wondering if this makes sense?

I would think that the fullscreen spinner must trump OR it shouldn't be displayed if there is a non-fullscreen spinner that is already running. At the same time, this implementation can get complex with having to communicate between the spinners, especially if say the non-fullscreen one completes, but the request behind the fullscreen is still going, which means the fullscreen spinner (which was previously hidden) must now be shown.

Thanks for the great library btw

**Comment by Napster2210** [comment]
@hhermas Communicating between spinners would make this simple library very complex. I am trying to make this library more smaller or lighter version. But thanx for your suggestion I'll keep in my mind for future features.
