### ISSUE TITLE
How to show spinner on top part of container

### ISSUE THREAD

**Issue by f3l1xss** [Napster2210/ngx-spinner#148]
Hi there, when having parent with long height, Spinner will still be displayed in the center of the parent which will typically cause it to be invisible. 
Is there any way to force the spinner to be at the top middle part?

FullScreen is not an option to me since I want some element in my DOM to be displayed when loading

**Comment by rspl-yuvraj** [comment]
@f3l1xss You can wrap `ngx-spinner` in `div` and set your required style to that `div`. Make sure have set `position: relative;` to that `div` and `fullScreen` is `false`.

**Comment by f3l1xss** [comment]
@rspl-yuvraj Hi Yuvraj, while it can be done that way, I kinda feel that it is a bit 'hacky' as the css then would have to target the div with specific animation type name and overwrite its margin properties (maybe there is a better way than using margin).

I ended up making the spinner fullscreen and making the background transparent as its neater that way

**Comment by bogdandanielb** [comment]
> @f3l1xss You can wrap `ngx-spinner` in `div` and set your required style to that `div`. Make sure you have set `position: relative;` to that `div` and `fullScreen` is `false`.

This can be included in the documentation.

**Comment by Napster2210** [comment]
@f3l1xss In next release I am planning to expose some classes for Spinner and Overlay as well which help you guys to extend/overwrite the styling.
