### ISSUE TITLE
Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]

### ISSUE THREAD

**Issue by mkydouglas** [Napster2210/ngx-spinner#149]
Hey guys..

Coul'd you help with this error?

I'm gonna send images to show you my configs and complete error message.

Thanks a lot!

![Screenshot_11](https://user-images.githubusercontent.com/40704841/91610706-2a9fe980-e950-11ea-936f-ba89b7b2224c.png)
![Screenshot_12](https://user-images.githubusercontent.com/40704841/91610708-2a9fe980-e950-11ea-994b-0071db123d97.png)
![Screenshot_13](https://user-images.githubusercontent.com/40704841/91610709-2a9fe980-e950-11ea-91e4-4f072a4af1dd.png)
![Screenshot_14](https://user-images.githubusercontent.com/40704841/91610712-2b388000-e950-11ea-830c-f810901a3370.png)
![Screenshot_15](https://user-images.githubusercontent.com/40704841/91610704-296ebc80-e950-11ea-9e4a-c01656904664.png)

**Comment by Napster2210** [comment]
@mkydouglas You should use `ngx-spinner` version 8. Please check ReadMe file.

**Comment by Napster2210** [comment]
@mkydouglas Use `v8.1.0` of `ngx-spinner`
