### ISSUE TITLE
When spinner is loaded, mouse clicks are disabled. but you can still trigger keyboard events.

### ISSUE THREAD

**Issue by Vandana-25** [Napster2210/ngx-spinner#150]
When spinner is loaded, mouse clicks are disabled. but you can still trigger keyboard events.

for example:
https://stackblitz.com/edit/angular-9kvtka?file=src%2Fapp%2Fapp.component.ts

In the above demo example, follow the steps to reproduce the issue.

1. Move <button nbButton status="success" (click)="showSpinner()">Start Spinner</button> inside <nb-card-body>
2. Navigate to start spinner button with keyboard. press once. spinner shows up. 
3. Continue pressing the enter key. The spinner triggers that as an event and keeps on loading the spinner again and again.

**Comment by Napster2210** [comment]
@Vandana-25 I need to work on this but great catch! Thanx for using this library.

**Comment by Napster2210** [comment]
It's resolved and available in [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)
