### ISSUE TITLE
Spinner doesnt show in Angular 10

### ISSUE THREAD

**Issue by nikoslyk2093** [Napster2210/ngx-spinner#151]
I installed ngx-spinner on my app and i cant make it show.. i followed all the instruction from getting started. Anyone has the same problem?

**Comment by Sidhava** [comment]
With Angular 10 and ngx-spinner version 10.0.1 the spinner works only in the ngAfterViewInit method for me.

**Comment by jonghshin** [comment]
It does not work on my Angular 10 project.

**Comment by andyb70** [comment]
No problems here with 10.2.4 although make sure you include the NgxSpinnerModule in your module file.
