### ISSUE TITLE
How to change the text/template through the options?

### ISSUE THREAD

**Issue by andyb70** [Napster2210/ngx-spinner#156]
I have a spinner on my app.component and I call this full page spinner from various places however I would like to supply different text, sometimes the text should be "Loading.." other times the text wants to be "Cancelling.." and so but I can't seem to change this through the show method, I have tried the following: -

`this.spinner.show(undefined, { template: 'Cancelling..'});`

but I still get the "Loading.." text which is defined on my base component?

**Comment by Napster2210** [comment]
@andyb70 Currently there is no option to change template text through options but you can define a variable in your component and pass this way:

```
<ngx-spinner
  bdColor="rgba(51,51,51,0.8)"
  size="medium"
  color="#fff"
  type="ball-scale-multiple"
>
  <p style="font-size: 20px; color: white">{loadingText}</p>
</ngx-spinner>
```

**Comment by sowna** [comment]
@Napster2210  is any option given to change template text through options now?
