### ISSUE TITLE
Option to disable fade animations?

### ISSUE THREAD

**Issue by Delubear** [Napster2210/ngx-spinner#158]
Can we get an option to disable the fade animations? And to have separate disables for fadeIn and fadeOut?  

When initializing in a child component and wanting the spinner to appear immediately, the fade shows the parent component elements (in fullscreen) before fading away.  It looks tacky and being able to disable it would be great.

**Comment by Napster2210** [comment]
@Delubear Thanx for the suggestion, I'll keep in mind.

**Comment by obrassard** [comment]
Hello, I found this issue while trying to achieve the same thing as @Delubear! 
Are you still considering this change?

I think we could add a new animation state and transitions (e.g. a `fadeOutOnly` state) to `NgxSpinnerComponent` and let users choose which animation they want to use by passing the start state in an `@Input`. This would allow us to easily customize the animation.

**Comment by Napster2210** [comment]
It's done and available in [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)
