### ISSUE TITLE
How to use multiple ngx-spinner object on single page

### ISSUE THREAD

**Issue by Feroz-Istar** [Napster2210/ngx-spinner#16]
How to use multiple ngx-spinner object on single page. how can i show/hide  each one of the using view child

**Comment by Napster2210** [comment]
@Feroz-Istar There is no such kind of functionality, but thanx for the suggestion. Will come up soon with the solution.

**Comment by alexandr-efimov** [comment]
any updates guys?

**Comment by sathishkumar94** [comment]
Hi Guys,

Its weird. Because, i want to use the spinner in multiple places which means, multiple api calls/pages. but dont have option to use multiple spinner.

Give me the update guys?

**Comment by KartikShankarappa** [comment]
Any update on this ?
I would really like to see this on stackblitz.

**Comment by Napster2210** [comment]
@Feroz-Istar @alexandr-efimov @sathishkumar94 @engemasa @KartikShankarappa I'll review @alexandr-efimov 's PR and merge it soon.

**Comment by dbykadorov** [comment]
@Napster2210 thank you!

**Comment by FARHANE** [comment]
Any update ?

**Comment by Napster2210** [comment]
@FARHANE give me few days will release soon. Was busy in other stuffs.

**Comment by KartikShankarappa** [comment]
Can we get a demo if this functionality on Stackblitz ?

**Comment by Napster2210** [comment]
Working on examples right now you'll get it soon.

**Comment by wizdow** [comment]
Any update ?

**Comment by Napster2210** [comment]
@KartikShankarappa Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4

**Comment by tonycesar** [comment]
thanks  https://stackblitz.com/edit/angular-utwjxi

**Comment by KartikShankarappa** [comment]
@Napster2210 , if we have more than one spinner running, how to deal with loading text for each of those ? 
Right now i have a use case with 5 spinners running simultaneously and each of the spinner is supposed to display different loading text. However, while these spinners are running, the text is overlapping which makes any of the text unreadable.
Any suggestions on how to handle this ?

**Comment by rspl-yuvraj** [comment]
@KartikShankarappa Can you post a screenshot of your problem, so I can understand better.

**Comment by KartikShankarappa** [comment]
![image](https://user-images.githubusercontent.com/10079319/79350028-ec57df80-7f04-11ea-8190-c97c37fc258d.png)

**Comment by rspl-yuvraj** [comment]
@KartikShankarappa In this case, you need to handle the order of spinners. Are you using 5 different types of spinners or just text is different?

**Comment by KartikShankarappa** [comment]
In my html I have 5 different spinners...
Something like this.
`<ngx-spinner
    [name]="AppConstants.SPINNER_COMMON"
    bdColor = "rgba(51, 51, 51, 0.8)"
    size = "large"
    color = "#fff"
    type = "ball-beat">
    <p style="font-size: 20px; color: white">Loading Fulfillment Search Data...</p>
</ngx-spinner>
<ngx-spinner
    [name]="AppConstants.SPINNER_COMMON1"
    bdColor = "rgba(51, 51, 51, 0.8)"
    size = "large"
    color = "#fff"
    type = "ball-beat">
    <p style="font-size: 20px; color: white">Something Else is Loading...</p>
</ngx-spinner>
<ngx-spinner
    [name]="AppConstants.SPINNER_COMMON2"
    bdColor = "rgba(51, 51, 51, 0.8)"
    size = "large"
    color = "#fff"
    type = "ball-beat">
    <p style="font-size: 20px; color: white">Today is a nice day...</p>
</ngx-spinner>
......and so on`

**Comment by rspl-yuvraj** [comment]
@KartikShankarappa Why you're using multiple spinners, I can see all the configuration for your spinners is the same except the **"Loading Text"**. You can set different **"Loading Text"** using some variable and changing the value of that variable periodically.

```
<ngx-spinner
    [name]="AppConstants.SPINNER_COMMON"
    bdColor = "rgba(51, 51, 51, 0.8)"
    size = "large"
    color = "#fff"
    type = "ball-beat">
    <p style="font-size: 20px; color: white">{{loadingText}}</p>
</ngx-spinner>


loadingText = 'Loading Some Search Data...';

setTimeout(() => {
this.loadingText = 'Something Else is Loading...';
}, 1000);

setTimeout(() => {
this.loadingText = 'Today is a nice day...';
}, 3000);

setTimeout(() => {
this.loadingText = 'It's done...';
}, 5000);
```

Instead of `setTimeout` you can perform some actions.

**Comment by KartikShankarappa** [comment]
@Napster2210 , i am using multiple spinners because I have more than one API call executing simultaneously, which will resolve in their own time. Hence, in my code I provided above, the spinner names are different.
