### ISSUE TITLE
property @fadeIn. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application

### ISSUE THREAD

**Issue by guypeled1** [Napster2210/ngx-spinner#160]
I am getting this error what should I do?

**Comment by rspl-yuvraj** [comment]
@guypeled1 Import `BrowserAnimationsModule` module in your `app.module.ts` file.

**Comment by guypeled1** [comment]
from where?

**Comment by rspl-yuvraj** [comment]
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

**Comment by guypeled1** [comment]
Thanks

**Comment by vothanhdo2602** [comment]
> @guypeled1 Import `BrowserAnimationsModule` module in your `app.module.ts` file.

it's not working for me :(
