### ISSUE TITLE
Unable to extend the service because models are not exported

### ISSUE THREAD

**Issue by marius-orha** [Napster2210/ngx-spinner#162]
I created my own LoadingService and I try to call NgxSpinnerService methods from it, but I get the following error:
![image](https://user-images.githubusercontent.com/11141236/102087527-6046e080-3e22-11eb-8b54-eaa04f86f7cd.png)

**Comment by marius-orha** [comment]
PRIMARY_SPINNER and Spinner should be exported too, as log as are used as parameters in NgxSpinnerService methods, which are public.

**Comment by Napster2210** [comment]
@marius-orha Thanx for the suggestion, I'll make that changes in next release.

**Comment by Napster2210** [comment]
It's done and available in [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)
