### ISSUE TITLE
Error in angular 11

### ISSUE THREAD

**Issue by abnet3** [Napster2210/ngx-spinner#163]
when i try to import it in my module i am facing this error 

Module '"../../../node_modules/ngx-spinner/ngx-spinner"' has no exported member 'NgxSpinnerModule'.ts(2305)

any solutions?

**Comment by alb-noah** [comment]
did you find the solution ?

**Comment by larspehrsson** [comment]
I had the same problem. I uninstalled spinner with 
`npm uninstall ngx-spinner `
and reinstalled with 
`npm install ngx-spinner --force `
That seems to have solved the problem.

**Comment by nickeeromo** [comment]
#165

**Comment by nickeeromo** [comment]
ngx-spinner doesn't officially support Angular 11 yet. The workaround does work, but there are some corporate setups that won't allow that :(

But there is an enhancement request open for official Angular 11 support here: #165

**Comment by Napster2210** [comment]
New version is available for Angular [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)

**Comment by Felipe-Castillo** [comment]
doesn't work in angular 11

**Comment by raghavshivi94** [comment]
Doesn't work with Angular. Gives so many errors related to 'Namespace xyx has no exported member FactoryDeclaration' etc.

**Comment by Napster2210** [comment]
@Felipe-Castillo @raghavshivi94 Please post your `package.json` here, I want to know exact version Angular and ngx-spinner.

**Comment by raghavshivi94** [comment]
@Napster2210 yes I my Angular version is 11 and ngx-spinner version was 12.0.0 thats why I was getting error. I changed the ngx-spinner version to 11.0.2 and its now working :-)

**Comment by Napster2210** [comment]
Because in `ngx-spinner` v12.0.0, I have enabled Ivy support because that you were getting that errors.
