### ISSUE TITLE
When copying code from demo website, no spaces before bdColor,

### ISSUE THREAD

**Issue by STEdirisuriya** [Napster2210/ngx-spinner#164]
I was trying to customize a spinner from [](https://napster2210.github.io/ngx-spinner/). When I'm copying the data it removes the space before keyword bdColor.

`<ngx-spinnerbdColor = "rgba(0,0,0,0)" size = "medium" color = "#616161" type = "ball-scale-multiple" [fullScreen] = "false"></ngx-spinner>`

**Comment by Napster2210** [comment]
@STEdirisuriya Thanx for pointing out.

**Comment by Napster2210** [comment]
It's done and available in [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)
