### ISSUE TITLE
Hiding does not happen when hide() is run outside zone.

### ISSUE THREAD

**Issue by nurfgun** [Napster2210/ngx-spinner#166]
I saw no problem until I came across some 3rd party asynchronous method. To emulate it :
```
this.spinner.show();
this.ngZone.runOutsideAngular(()=>{
  setTimeout(()=>{
    this.spinner.hide();
  }, 2000);
});
```
In this scenario, the spinner component is marked for a check but a new change detection cycle is not run. 

Changing 
```
this.changeDetector.markForCheck(); 
```
to 
```
this.changeDetector.detectChanges();
```
in NgxSpinnerComponent's ngOnInit

will fix this.

**Comment by Napster2210** [comment]
@nurfgun Thanx for pointing out I will make this change in next release.

**Comment by Napster2210** [comment]
It's done and available in [v11](https://github.com/Napster2210/ngx-spinner/releases/tag/v11.0.0)

**Comment by nurfgun** [comment]
@Napster2210  👍
