### ISSUE TITLE
How to customize image of spinner ?

### ISSUE THREAD

**Issue by vietson** [Napster2210/ngx-spinner#17]
hello !
I can customize image of spinner ?

Thanks !

**Comment by Napster2210** [comment]
@vietson There is no such functionality to use image as spinner. I'm using just HTML & CSS for spinner. So you can not use custom spinner as of now, you have to choose one of that 50+ spinners. You can find list of spinners in [Demo](https://napster2210.github.io/ngx-spinner/).

**Comment by vietson** [comment]
Thank for your reply
I'm understand !

**Comment by shan75** [comment]
Hi, I am using this spinner in one of my project which is working great. Especially multi loader is perfect.  I can't figure out one particular thing. For example, you got size attribute which sets the size of spinner. It is small , medium, large etc... Unfortunately, small is too small or medium is too big for me.  I want the spinner size to be in-between.  I have have looked at the Load Awesome website.
I want this particular one. I am not sure how to get that. Can some one please help?
<div class="la-line-spin-fade la-dark">
