### ISSUE TITLE
ngx-spinner issue with angular 9 to support the IE 11 with ES5

### ISSUE THREAD

**Issue by vaishnavravi33** [Napster2210/ngx-spinner#170]
I want to run my angular 9 application in IE 11 and I installed the "ngx-spinner v10.0.01".

I need help with this issue.

When I compile the angular 9 application for the ES5 it is throwing the error -

Error - Error: getInternalNameOfClass() called on a non-ES5 class: expected NgxSpinnerService to have an
inner class declaration.

Compiling ngx-spinner : module as esm5
Warning: Invalid constructor parameter decorator in D:/Ravindra_Workplace/Projects/GreenTweed/Code/NGv09SMS/node_modules/ngx-spinner/fesm2015/ngx-spinner.js:

![image](https://user-images.githubusercontent.com/24837842/107774324-dbfed400-6d64-11eb-9554-46656fe99fb7.png)

**Comment by Napster2210** [comment]
@vaishnavravi33 You should use appropriate version of `ngx-spinner` as your application is in Angular v9 then use version `v9.0.1` for `ngx-spinner`.
