### ISSUE TITLE
Changing ngx-spinner name causes spinner to not be displayed anymore

### ISSUE THREAD

**Issue by razvanbh** [Napster2210/ngx-spinner#172]
I've create a [stackblitz ](https://stackblitz.com/edit/angular-ubrvk1?file=src/app/app.component.ts) to reproduce this issue.
When you load the page show and hide buttons work. If you press the change name button the show and hide actions stop working.

**Comment by Loisis** [comment]
I have the same issue. The spinner works only with the default name "primary". For all other names no spinner is shown.

**Comment by patelvimal** [comment]
@Napster2210 Here is the pull request for this bug. Please review it.
https://github.com/Napster2210/ngx-spinner/pull/177

**Comment by Napster2210** [comment]
Thanks @patelvimal for PR. This has been resolved and will available in latest version [v13.1.1](https://www.npmjs.com/package/ngx-spinner/v/13.1.1)

**Comment by Aball985** [comment]
this same issue appears to be happening again? in v17 once I add a name it breaks functionality then if I make it "primary" it works ??
