### ISSUE TITLE
ngb-modal and ngx-spinner

### ISSUE THREAD

**Issue by vbenavidesa** [Napster2210/ngx-spinner#174]
I tried to make this spinner work on a modal window, problem is that I already have a spinner on a card in the main component for when I fetch data from my service, now when I open the modal and activate the spinner it goes for the main window spinner size and not the modal size, it might be cuz its the same tags but I was wondering if there can be multiple instances of this and how could I call one or other instance.

**Comment by vbenavidesa** [comment]
I missed part of the documentation, I found the solution, sorry for the issue.

**Comment by Marrafeiro** [comment]
you could put here the solution or then delete the post.
