### ISSUE TITLE
Show Spinner until APP_INITIALIZER finishes

### ISSUE THREAD

**Issue by 123NeNaD** [Napster2210/ngx-spinner#175]
Hi, I also created an Stackoverflow question for this:
https://stackoverflow.com/questions/66299421/show-ngx-spinner-until-app-initializer-finishes

So, I want to display spinner until APP_INITIALIZER finishes. I put spinner tag in "index.html" but I don't know how to activate it. From what file can I activate it? I tried "app.component.ts" and "main.ts".

Thanks in Advance

**Comment by Napster2210** [comment]
This functionality is related with Angular, I think you need create some factory function and need pass dependency of `ngx-spinner` into that function and inside that function you need to call `ngx-spinner` service. But still I am not sure about `APP_INITIALIZER` will wait for that or not. You need to handle this manually in your application.

**Comment by DwieDima** [comment]
@123NeNaD have you found a working solution yet to use `ngx-spinner` insider `APP_INITIALIZER`?
