### ISSUE TITLE
Issue when used in lazy load module

### ISSUE THREAD

**Issue by laurentbellec** [Napster2210/ngx-spinner#176]
Could BrowserAnimationsModule be removed from ngx-spinner.module ?

**Comment by m-bagnarelli** [comment]
this issue has something to do with this error I am facing? 
I´m trying to use ngx-spinner in lazy loaded modules.

Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by laurentbellec** [comment]
yep, same error

**Comment by chentong98** [comment]
I also facing this issue how to fixed yah ?

**Comment by mlc-mlapis** [comment]
Yep, the problem was introduced by the commit:
https://github.com/Napster2210/ngx-spinner/commit/58af309502ae257b6a2bf60bef50034680c7cf0c
in this module file:
https://github.com/Napster2210/ngx-spinner/commit/58af309502ae257b6a2bf60bef50034680c7cf0c#diff-ddb8b1fedc5951918dceeed3835cfb59335f134bf85b3f8900a8859babd29bd8
````
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
...
@NgModule({
  imports: [
    CommonModule,
    BrowserAnimationsModule
  ],
...
```

**Comment by Napster2210** [comment]
I will remove it in next release.

**Comment by z3v0k** [comment]
same error!

**Comment by Napster2210** [comment]
@laurentbellec @m-bagnarelli @chentong98 @mlc-mlapis @z3v0k Can you please try the latest version **v11.0.1**?

**Comment by mlc-mlapis** [comment]
@Napster2210 It works as expected now on our side with v11.0.1. Thanks. 👍

**Comment by chentong98** [comment]
@Napster2210  yes, is works now thanks~

**Comment by m-bagnarelli** [comment]
@Napster2210 It works now. Thanks !!
