### ISSUE TITLE
I am getting two spinner if I use the <ngx-spinner></ngx-spinner> in any component's template. How to remove the default spinner.

### ISSUE THREAD

**Issue by shaswat10mishra** [Napster2210/ngx-spinner#178]
I have installed the ngx-spinner in my app, added in imports array of the module but not injected in any of the templates. Now when I am using its methods show() & hide() in API calls I am getting a default spinner with **"please wait"** text. 
Now If I use any other type of this spinner (**type = "square-jelly-box"**), I am getting two spinners overlapped. 
My question is :- I want to remove that default spinner (**type="ball-spin-clockwise"**) and use that (**type = "square-jelly-box"**) one only. How can I achieve this?

**Comment by Napster2210** [comment]
@shaswat10mishra Can you please create sample code on https://stackblitz.com/ ?

**Comment by Napster2210** [comment]
Closing the issue due to inactivity. Feel free to open if someone faced the same with sample code.
