### ISSUE TITLE
customize loading text 

### ISSUE THREAD

**Issue by AhmedMohamed1110** [Napster2210/ngx-spinner#18]
how to customize loading text  as using multiple lines with different classes and tags of HTML and using icons
example: 
loadingText:"loading"
I want to write multiple lines with different classes and tags of HTML as:
< h1 >loading ...< h1 >
< span > please wait < br/ > .......</ span >

**Comment by Napster2210** [comment]
Currently it supports string only, for your requirement I have to give support of html as input.

**Comment by AhmedMohamed1110** [comment]
okay thank u , but do u have any idea for making break line between strings without using a <br> element inside loadingText?

**Comment by AhmedMohamed1110** [comment]
????????

**Comment by Napster2210** [comment]
I'm not sure but may be using "\n" you can achieve this.

**Comment by Napster2210** [comment]
@AhmedMohamed1110 Above thing is working for you?

**Comment by AhmedMohamed1110** [comment]
no

**Comment by AhmedMohamed1110** [comment]
@Napster2210  no

**Comment by Napster2210** [comment]
@AhmedMohamed1110 Then I have to look into it. Maybe new feature.

**Comment by AhmedMohamed1110** [comment]
@Napster2210  OK, I will wait you

**Comment by Napster2210** [comment]
@AhmedMohamed1110 This has been resolved and will be available in the current release([v6.1.1](https://github.com/Napster2210/ngx-spinner/releases/tag/v6.1.1))
