### ISSUE TITLE
@HostListener('document:keydown', ['$event']) blocks keyboard input

### ISSUE THREAD

**Issue by vlad-cirstean** [Napster2210/ngx-spinner#182]
Hello, 
I wonder what is the purpose of [this](https://github.com/Napster2210/ngx-spinner/commit/7c13ee9abeec5c36a26318f84fde30a54036f6c9#diff-ac6b876f9fcb73569b9f0635e242b0e12aa9444c5fd164a37b0f8f9fc9557f55R139) key interceptor?

I use the spinner for an async validator and the latest version blocks any keyboard events (tested on Chrome, Firefox and Safari) 
<img width="460" alt="Screenshot" src="https://user-images.githubusercontent.com/47884248/117266664-2b353c00-ae5e-11eb-8d57-23424b1fa794.png">

**Comment by Napster2210** [comment]
@vlad-cirstean It was implemented due to #150

**Comment by iron2414** [comment]
Created a pull request, please review and accept if there are no problems with it.
Good libary btw! :)

**Comment by iron2414** [comment]
@Napster2210

**Comment by i-aleksandrov** [comment]
Any progress on this one? I have a use case where I have input fields in a modal window which need to be responsive while a potentially longer operation is loading in a separate component on the page.

**Comment by iron2414** [comment]
The owner of this repository didn't react to my pull request yet. However I fixed it for the Angular 11 version. You can use that temporary, till my pull request gets acceoted, or some other solution gets implemented.

**Comment by Napster2210** [comment]
This has been fixed in https://github.com/Napster2210/ngx-spinner/releases/tag/11.0.2

**Comment by iron2414** [comment]
That commit is not gonna work.  If you are not in fullscreen, and you mask a certain div, and the focus is inside of it. Then now you can press buttons on the keyboard, its going through. Please checkout my pull request, that fixes it properly
