### ISSUE TITLE
Please add support for Angular 12

### ISSUE THREAD

**Issue by pavankjadda** [Napster2210/ngx-spinner#184]
Angular 12 released today, please add support for it

**Comment by mosheboker1** [comment]
Can you merge it please?

**Comment by mac-bhaird** [comment]
Checking in on this, is this going to happen soon?

**Comment by Napster2210** [comment]
@pavankjadda @mosheboker1 @mac-bhaird @djonmayer @cwtwcz @stolato @Sarah-JJ @nicks-passiert@cl-kazumi-nakajima
Release new version v12.
