### ISSUE TITLE
How about supporting state change via a @input() show? on the ngx-spinner?

### ISSUE THREAD

**Issue by hidegh** [Napster2210/ngx-spinner#186]

**Comment by Napster2210** [comment]
@hidegh It's already there in v11. Please check https://github.com/Napster2210/ngx-spinner#whats-new

**Comment by lyvyu** [comment]
Hello guys, 

first thanks for an amazing library and continuous updates, amazing work !!!

Now, it seems that displaying spinner from template using `[showSpinner]='true'` seems not to be working. Even in stakblitz described in readme.

Perhaps you guys forgot to check the value on first load, pls check on that !!

Thanks in advance.
