### ISSUE TITLE
Cover code with unit tests

### ISSUE THREAD

**Issue by glenstaes** [Napster2210/ngx-spinner#187]
Given the number of weekly downloads using npm, I think the coverage of unit tests should be better.

Having only a 'should create' test for the component and service offers little confidence regarding regression effects to companies considering the package.

**Comment by Napster2210** [comment]
@glenstaes Sure @glenstaes . Thanx for the interest.

**Comment by Napster2210** [comment]
Thanks a lot @AlexHoisan for your efforts. Now unit test cases will be available in latest version [v13.1.1](https://www.npmjs.com/package/ngx-spinner/v/13.1.1)
