### ISSUE TITLE
ngx-spinner gives a lot of "static ɵprov: ɵngcc0.ɵɵInjectableDef" errors

### ISSUE THREAD

**Issue by sebit-dogancoruh** [Napster2210/ngx-spinner#189]
ngx-spinner gives a lot of "static ɵprov: ɵngcc0.ɵɵInjectableDef" errors with the newest version of angular.

**Comment by rspl-yuvraj** [comment]
@sebit-dogancoruh  Which version of Angular you are using?

**Comment by kombasltd** [comment]
Same here, Angular 11:

```
static ɵfac: i0.ɵɵFactoryDeclaration<NgxSpinnerModule, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-spinner/lib/ngx-spinner.module.d.ts:7:21 - error TS2694: Namespace '"J:/Projekte/KProject/client-app/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

7     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxSpinnerModule, [typeof i1.NgxSpinnerComponent, typeof i2.SafeHtmlPipe], [typeof i3.CommonModule], [typeof i1.NgxSpinnerComponent]>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-spinner/lib/ngx-spinner.module.d.ts:8:21 - error TS2694: Namespace '"J:/Projekte/KProject/client-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

8     static ɵinj: i0.ɵɵInjectorDeclaration<NgxSpinnerModule>;
```

**Comment by Napster2210** [comment]
@sebit-dogancoruh @kombasltd Which version of `ngx-spinner` you are using?

**Comment by kombasltd** [comment]
I tried to install latest version.

As I said, now I am using

`"ngx-spinner": "^9.0.2",`

again without getting this error (used this version in an other project already without any problem).

**Comment by Shams0045** [comment]
@kombasltd I had same problem, in my case by default I installed ngx-spinner version 10 which is not capable with Angular version 11. Therefore, deleted ngx-spinner version 10 and installed version 11 (npm i ngx-spinner@11.0.0) for Angular 11.

**Comment by Napster2210** [comment]
@kombasltd With Angular `v11`, please try to use `ngx-spinner` `v11.0.2`. You can use the command `npm i ngx-spinner@11.0.2` to install that specific version. You are getting above errors because in the latest version(`v12`) I have enabled Ivy support partially which uses different compilation from previous versions.

**Comment by Napster2210** [comment]
Closing this, feel free to reopen if anyone faced the same issue.
