### ISSUE TITLE
Failing to activate spinner using [showSpinner]

### ISSUE THREAD

**Issue by joelmuskwe** [Napster2210/ngx-spinner#193]
Current Environment:
```
  Node : 14.17.3
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.7.1
  @nrwl/cli : 12.7.1
  @nrwl/cypress : 12.7.1
  @nrwl/devkit : 12.7.1
  @nrwl/eslint-plugin-nx : 12.7.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.1
  @nrwl/linter : 12.7.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.7.1
  @nrwl/storybook : 12.7.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

I have imported NgxSpinnerModule and have added the CUSTOM_ELEMENTS_SCHEMA schema but when i try to initiate the spinner using [showSpinner] nothing happens.

```
<ngx-spinner
  bdColor="rgba(51,51,51,0.8)"
  size="medium"
  color="#fff"
  type="ball-scale-multiple"
  [showSpinner]="true"
>
</ngx-spinner>

```

**Comment by AlexCs389** [comment]
same problem

**Comment by Prontsevich** [comment]
I also have this problem in some cases. In one component it works, in another not.

**Comment by MeltedFreddo** [comment]
For me, the spinner will not appear on initial load, but will start to appear from the second time the controlling variable is toggled.

**Comment by webcrunch-zh** [comment]
Same here, any updates?

**Comment by MeltedFreddo** [comment]
In ngx.spinner.component.ts there is this inside the ngOnChanges function:

`if (changedProp.isFirstChange()) {
          return;
        }`

Which seems suspicious to me

**Comment by mykolav** [comment]
Same problem here.  
Here's my workaround:
```typescript
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-spinner',
  template: `
    <ngx-spinner
      bdColor="rgba(0,0,0,0.5)"
      size="medium"
      color="#fff"
      type="line-scale"
      [zIndex]="3"
      [fullScreen]="false"
      [showSpinner]="_show"
    >
    </ngx-spinner>
  `,
})
export class SpinnerComponent implements OnChanges {
  @Input() showSpinner = false;
  _show = false;

  ngOnChanges(changes: SimpleChanges): void {
    const showSpinnerChange = changes['showSpinner'];
    if (showSpinnerChange) {
      if (showSpinnerChange.isFirstChange()) {
        // A workaround for [Failing to activate spinner using \[showSpinner\]]
        // (https://github.com/Napster2210/ngx-spinner/issues/193)
        this._show = !this.showSpinner;
        setTimeout(() => (this._show = this.showSpinner));

        return;
      }

      this._show = this.showSpinner;
    }
  }
}

```

**Comment by JacobF7** [comment]
Same issue happening here. Any updates on this? 

Currently, as a workaround, I've managed to show the spinner by calling:

`this.spinner.show(...)` inside onInit

**Comment by Napster2210** [comment]
@joelmuskwe @AlexCs389 @Prontsevich @MeltedFreddo @webcrunch-zh @mykolav @JacobF7 At initial load, the spinner object loads with all the default values. So instead of setting `true` as initial value for `showSpinner` just assign one variable(defaults to `false`) and make it `true` with `setTimeout`. Its related with the error **NG0100**: https://angular.io/errors/NG0100

You can refer this example: https://stackblitz.com/edit/angular-q6exsz

**Comment by kevalbhatt** [comment]
I was looking for multiple loaders and wanted to handle using the component property.

SO I have created my own component and added the name and service management from that only.

`import {
  Component,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges,
} from '@angular/core';
import { Size, NgxSpinnerService } from 'ngx-spinner';

@Component({
  selector: 'app-spinner',
  template: `
    <ngx-spinner
      [name]="_name"
      [bdColor]="options.bdColor"
      [size]="options.size"
      [color]="options.color"
      [type]="options.type"
      [fullScreen]="options.fullScreen"
      [zIndex]="options.zIndex"
    >
      <p style="color: white">Loading ...</p>
    </ngx-spinner>
  `,
})
export class SpinnerComponent implements OnChanges, OnInit {
  @Input() showSpinner = false;
  @Input() options: {
    bdColor?: string;
    size?: Size;
    color?: string;
    type?: string;
    fullScreen?: boolean;
    zIndex?: number;
  } = {};
  _name = '';

  constructor(private spinner: NgxSpinnerService) {
    this._name = `${Math.random()
      .toString(36)
      .slice(2, 7)}_${new Date().getTime()}`;
  }

  ngOnInit() {
    this.options = Object.assign(
      {
        bdColor: 'rgba(0, 0, 0, 0.8)',
        size: 'medium',
        color: '#fff',
        type: 'line-scale-party',
        fullScreen: true,
        zIndex: 99999,
      },
      this.options
    );
  }

  _showSpinner(name: string) {
    this.spinner.show(name);
  }

  _hideSpinner(name: string) {
    this.spinner.hide(name);
  }

  ngOnChanges(changes: SimpleChanges): void {
    const showSpinnerChange = changes['showSpinner'];
    if (showSpinnerChange) {
      showSpinnerChange.currentValue
        ? this._showSpinner(this._name)
        : this._hideSpinner(this._name);
    }
  }
}
`
and this how you use it 

`<app-spinner [showSpinner]="loading"></app-spinner>`
