### ISSUE TITLE
Spinner with Indeterminate time

### ISSUE THREAD

**Issue by jbchan07** [Napster2210/ngx-spinner#20]
I did not find a way to use the ngx-spinner for indeterminate time. API response time, in development env, is unpredicatable and I need a way for the spinner to stop immediately after receiving the response. Please suggest.

**Comment by Napster2210** [comment]
You can use async await for that

**Comment by Napster2210** [comment]
@jbchan07 Can you please share your code snippet?

**Comment by rspl-yuvraj** [comment]
By using `async await` or using `Promise` you can handle this type scenario.
