### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by feliperodriguez44** [Napster2210/ngx-spinner#202]
hey guys, lets apply v13 updates. can i help if u want =)

**Comment by Napster2210** [comment]
@feliperodriguez44 Sure, I will release the latest version very soon with Angular 13 update.

**Comment by feliperodriguez44** [comment]
tksss

**Comment by GabrielKar** [comment]
I have your code, working on angular 13, and witch eslint support. If you give me access to create push and pull request I can do it right now.

**Comment by josephsieang** [comment]
@Napster2210 Can I know when your package could support Angular 13?

**Comment by maku** [comment]
@Napster2210 would like to convert my project to ng13 - would be great when you update ngx-spinner to v13 - thank you...

**Comment by Napster2210** [comment]
@maku I will release v13 by today/tomorrow.

**Comment by GabrielKar** [comment]
I already pushed changes to my fork and I have been made a pull rquest,
that you have to accept or make some coments.

śr., 8 gru 2021, 11:18 użytkownik Martin ***@***.***> napisał:

**Comment by Napster2210** [comment]
@feliperodriguez44 @GabrielKar @josephsieang @maku Latest version v13 is now available.
https://www.npmjs.com/package/ngx-spinner/v/13.0.0
