### ISSUE TITLE
Interceptor Implementation

### ISSUE THREAD

**Issue by raj111** [Napster2210/ngx-spinner#21]
Hi,

When will be this feature available? Is there any specific time frame.

Thanks.

**Comment by Napster2210** [comment]
Hopefully in next 10-15 days

**Comment by Et3rnal** [comment]
Glad I saw this before I look alternative 💃

**Comment by Et3rnal** [comment]
Any news on thins?

**Comment by raj111** [comment]
@Napster2210 Any update on this feature?

**Comment by Napster2210** [comment]
As of now you can find solution in #32

**Comment by Napster2210** [comment]
Please refer #32 for more update.
