### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by emouawad** [Napster2210/ngx-spinner#22]
NgxSpinnerComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: false'. Current value: 'ngIf: true'.
    at viewDebugError (core.js:7386)
    at expressionChangedAfterItHasBeenCheckedError (core.js:7374)
    at checkBindingNoChanges (core.js:7476)
    at checkNoChangesNodeInline (core.js:10337)
    at checkNoChangesNode (core.js:10326)
    at debugCheckNoChangesNode (core.js:10929)
    at debugCheckDirectivesFn (core.js:10857)
    at Object.eval [as updateDirectives] (NgxSpinnerComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:10846)
    at checkNoChangesView (core.js:10225)

At:

<div class="black-overlay" *ngIf="showSpinner" [ngStyle]="{'background-color': bdColor}"> <div [class]="spinnerClass" [style.color]="color"> <div *ngFor="let i of divArray"></div> </div> <p *ngIf="loadingText" [style.color]="color">{{loadingText}}</p> </div>

My Use:

 public subjectLoading = new Subject();

this.subjectLoading.subscribe((p) => {
      if (p === true) {
        this.spinner.show();
      } else {
        this.spinner.hide();
      }
    })

**Comment by rspl-yuvraj** [comment]
@emouawad It happens if a value of `p` has been changed immediately. You can use any lifecycle hook of Angular or you can use some delay `setTimeout()`(weird hack).

**Comment by nishit-rspl** [comment]
@emouawad this should work fine with production build

**Comment by nishit-rspl** [comment]
@rspl-yuvraj i get below error in my local environment which suggests that this needs to be fix in component. I do not get this error on production build
![image](https://user-images.githubusercontent.com/27686506/43196743-971f27a4-9026-11e8-8b84-f0122371a29d.png)

**Comment by rspl-yuvraj** [comment]
@emouawad @nishit-rspl  The issue has been already logged in Angular itself:
https://github.com/angular/angular/issues/17572
You can find possible solutions.
