### ISSUE TITLE
Default type

### ISSUE THREAD

**Issue by mdantonio** [Napster2210/ngx-spinner#222]
It seems that starting from version 13.1 there is no longer a default type.

Up to version 13.0 if no type was specified a default spinner was shown, but now a warning is raised:

```
 Property "type" is missed. Please, provide animation type to <ngx-spinner> component and ensure css is added to angular.json file
```

Is there a way to set a default type for the whole project and avoid to put the same type="xyz" on all the pages?

For example by setting a configuration when importing the NgxSpinnerModule into the NgModule

```
@NgModule({
	imports: [
                ...
		NgxSpinnerModule.forRoot({
			type: "my-default-type",
		})
	],
```

Thank you for your help!

**Comment by ennjin** [comment]
@mdantonio Hi. I've added a new pull request for feature you're described above. So waiting for review by @Napster2210 😸

**Comment by mdantonio** [comment]
Thank you!!

**Comment by Napster2210** [comment]
It is available in the latest version.
https://www.npmjs.com/package/ngx-spinner/v/14.0.0

**Comment by mdantonio** [comment]
Thank you!
