### ISSUE TITLE
How to vertical center a spinner inside a row with col grid ?

### ISSUE THREAD

**Issue by titaii2** [Napster2210/ngx-spinner#225]
Spinner won't center all over my columns inside a row from grid layout.

```
<div` class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-3">
  </div>
  <div class="col-md-3">
  </div>
  <div class="col-md-3">
  </div>
  <div class="col-md-3">
  </div>
  <ngx-spinner name="spinnerName" [fullScreen]="false" bdColor="rgba(34, 39, 54, 0.9)" 
  size="medium" color="rgb(66, 168, 191)" type="ball-newton-cradle">En attente des données...</ngx-spinner>
</div>
```

![image](https://user-images.githubusercontent.com/18117568/163415701-6cc27dc0-b517-4ec7-b9ad-be54dc781adc.png)

**Comment by Napster2210** [comment]
@titaii2 Set `position: relative;` in your css class `row` and then try again.

**Comment by titaii2** [comment]
> @titaii2 Set `position: relative;` in your css class `row` and then try again.

Thanks for your answer.
Already did it by checking others issues but it doesn't change anything unfortunately.

**Comment by Napster2210** [comment]
@titaii2 Can you please create Stackblitz for this scenario so I can look into it thoroughly?

**Comment by titaii2** [comment]
Finally found it.

I'm using this template : http://skote-v-dark.angular.themesbrand.com/dashboard
And for some reason, in a scss file, this line made the spinner stuck at the bottom of the container : 
![image](https://user-images.githubusercontent.com/18117568/163603684-279ab31e-ed04-404a-881c-225468d39b16.png)

So I just overwritted this line in my style.scss and it is now looking "normal"
![image](https://user-images.githubusercontent.com/18117568/163603848-99e92101-9ab5-4e39-a01f-f4fcc21abfba.png)

Except the fact that the message and the spinner are a bit too close and I don't know why ?

(Couldn't provide a Stackblitz for reproducing perfectly this part of my project)
