### ISSUE TITLE
increase text size

### ISSUE THREAD

**Issue by Amit18Singh** [Napster2210/ngx-spinner#23]
how to increase size of loadingText??

**Comment by Amit18Singh** [comment]
i'm using it in typescript but its not working for me
can you tell me how yo use your css in it

<ngx-spinner class="black-overlay"
  bdColor="rgba(51,51,51,0.8)"
  size="medium"
  color="#fff"
  [loadingText]="loadingtext"
  type="ball-scale-multiple">
</ngx-spinner>


.black-overlay > p {
  font-size: 35px;
}

**Comment by rspl-yuvraj** [comment]
@Amit18Singh  Try to override my class like this:
`.black-overlay > p {
font-size: 35px;
}
<ngx-spinner
bdColor="rgba(51,51,51,0.8)"
size="medium"
color="#fff"
[loadingText]="loadingtext"
type="ball-scale-multiple">
`
Let me know if it works for you.

**Comment by rspl-yuvraj** [comment]
@Amit18Singh You don't need to change in `node_modules`, just write that CSS class in your component's CSS(maybe `app.component.css`)

**Comment by Amit18Singh** [comment]
its not working for me if i'm writing it in my css file.

my html:
<ngx-spinner bdColor="rgba(51,51,51,0.8)" size="medium" color="#fff" [loadingText]="loadingtext" type="ball-scale-multiple">

my css:
.black-overlay > p { font-size: 35px; }

**Comment by Et3rnal** [comment]
Just find your style.css and put this code inside it
.black-overlay > p {
font-size: 35px;
}

Otherwise in your html page add the
<style>
.black-overlay > p {
font-size: 35px;
}
</style>

You better add it to your style file "style.css"

**Comment by Amit18Singh** [comment]
after adding it into  "style.css" its working.
thank you! @Et3rnal @rspl-yuvraj
