### ISSUE TITLE
When template is used a warn message appear in the console

### ISSUE THREAD

**Issue by dr-star** [Napster2210/ngx-spinner#233]
Hello, 

`
<ngx-spinner  template="<img src="..." alt="..."/>" >
</ngx-spinner>
`

The loader is shown properly, the only "problem" is a warn message in console even if ngx-spinner is correctly configured.

`
[ngx-spinner]: Property "type" is missed. Please, provide animation type to <ngx-spinner> component
        and ensure css is added to angular.json file
`

Is it the expected behaviour?

**Comment by Napster2210** [comment]
Yes, now you must need to pass type and import particular css for that type of spinner. It will help you to reduce the bundle size.

**Comment by Napster2210** [comment]
@dr-star Can you please test this in v15: https://www.npmjs.com/package/ngx-spinner
