### ISSUE TITLE
Angular 15 support 

### ISSUE THREAD

**Issue by mac-bhaird** [Napster2210/ngx-spinner#237]
Please update to support Angular 15 :)

**Comment by ICTAPhogeschool** [comment]
Yes, please update to support angular 15.
Thanks.

**Comment by Davidgimenez1997** [comment]
I have seen a PR about this task, do you know when it merges?
Thanks

**Comment by harmeetsingh17** [comment]
Yes, the update is required. any estimate of when it will be released?

**Comment by Napster2210** [comment]
New version will be released by end of this week.

**Comment by BrandonSchreck** [comment]
Any update?

**Comment by doughlass** [comment]
@Napster2210 any update on when this will be released?

**Comment by gadipati** [comment]
> New version will be released by end of this week.

We are waiting for it...

**Comment by Napster2210** [comment]
Sorry guys, I am away from my place for few days. I will surely release by early next week.

**Comment by Dark0rion** [comment]
> Sorry guys, I am away from my place for few days. I will surely release by early next week.

Any update??

**Comment by Napster2210** [comment]
@gadipati @mac-bhaird @Dark0rion @BrandonSchreck @ICTAPhogeschool @doughlass @harmeetsingh17 @Davidgimenez1997 New version is released for v15: https://www.npmjs.com/package/ngx-spinner

**Comment by doughlass** [comment]
@Napster2210 would you like to open up and accept Maintainers for future Releases of Angular?
