### ISSUE TITLE
Size of ngx-spinner in bundle 

### ISSUE THREAD

**Issue by maku** [Napster2210/ngx-spinner#24]
In my current project I determined the size of the libraries used in the delivery package.  (Build with angular cli 6.0.x -> ng build --prod)

I realized that ngx-spinner has a size of 454.6 KB (ngx-spinner.ngfactory.js.pre-build-optimizer.js: 240.63 KB, ngx-spinner.umd.js_ 212.62 KB)

This seems really big. 
So my question:  is this stuff really needed for delivering?

**Comment by rspl-yuvraj** [comment]
@maku  The library contains so many CSS classes because all the spinners are created using HTML and CSS only. There is no any other dependencies to generate spinner. But, thanx for the point I'll try to reduce an overall size of library in next release.

**Comment by maku** [comment]
@rspl-yuvraj Thank you very much for your effort. Maybe it would be an option to define which kind of spinner you want with an import or something else.  From my point of view, I use exactly one kind of spinner per app... So to have all available spinners in the distribution is really not necessary. Thx

**Comment by rspl-yuvraj** [comment]
@maku Thanx for the views. I'll try to find some way to import CSS class for that. I'm using some classes for each spinner(50+ spinners). Do you have any idea how can I import specific class for particular spinner type?

**Comment by maku** [comment]
I have to admit that I don't have a good answer for this question (especially with the approach you use now -> using styleUrl in NgxSpinnerComponent and ViewEncapsulation.Emulated). 

It seems clear that the css definition has to be separated for every spinner type. Then we would need a mechanism to load only the css for a certain spinner type. Maybe by a provider which has to be configured and in a dynamically way...

**Comment by matzmz** [comment]
I have the same problem, the bundle is too big.
In order to enable the tree-shaking mechanism you could create a base-component (with the spinner logic) and the extend the base-component injecting the specific css (one for type).

Doing this I think that it will be possible to minimize the bundle size.

**Comment by lonix1** [comment]
@matzmz Yes I think that is how other libraries handle this problem.

**Comment by jymaps** [comment]
I think you can start by letting people import manually the css files they need from Load Awesome.

**Comment by Napster2210** [comment]
@maku @matzmz @lonix1 @jymaps Working on this one, will come up with solution soon. Thanx for your support.

**Comment by Silvac34** [comment]
Any update on this topic ?

**Comment by rspl-yuvraj** [comment]
@Silvac34 Currently working on this, it'll be available in the next release. Maybe in 4-5 days.

**Comment by Silvac34** [comment]
Nice to hear that ! Waiting for the new release then

**Comment by jpike88** [comment]
This is preventing me from using this library, that’s way too big just to show a spinner

**Comment by rspl-yuvraj** [comment]
@jpike88 I'm planning two approaches for the same.

1. Create a lighter version of the library with a few standard spinners
2. Release a new version of the library which manage itself the issue

**Comment by jymaps** [comment]
What's the status on this?

**Comment by rspl-yuvraj** [comment]
@jymaps I'm still struggling with the proper implementation of this problem? Do you have any hint?

**Comment by jymaps** [comment]
I think one option is to let people import the css style that they need. I can see that loadAwesome has the animations into individual css files. In my case, I am only using one spinner animation. So this will help a lot in decreasing my bundle size. The I can load the css file into my project like this https://egghead.io/lessons/angular-lazy-load-css-at-runtime-with-the-angular-cli. So the spinner will not need to know the classname of the animation.

**Comment by tspicer** [comment]
Any update on this? The package is rather large, even compressed. Google ranking is complaining about all the unused CSS. I suppose we can hack the CSS a bit, but that will get messy

**Comment by Silvac34** [comment]
Still no update on this ?

**Comment by bogdandanielb** [comment]
Any good news in 2020 related to bundle size?

**Comment by chitra-c** [comment]
@Napster2210 any update on reducing the bundle size ?

**Comment by jocafi** [comment]
Any news on how to reduce the bundle size of ngx-spinner.js ?

**Comment by Napster2210** [comment]
Thanks a lot @ennjin for your efforts. Now smaller bundle size will be available in latest version [v13.1.1](https://www.npmjs.com/package/ngx-spinner/v/13.1.1)

@maku @tspicer @bogdandanielb @jpike88 @jocafi @matzmz @chitra-c @Silvac34 @jymaps
