### ISSUE TITLE
Combatibility issues

### ISSUE THREAD

**Issue by apalasopoulos1986** [Napster2210/ngx-spinner#248]
Not adding the animations folder in ngx-spinner folder in node_modules. Using "@angular/common": "10.0.8", "@angular/core": "10.0.8","ngx-spinner": "^10.0.1",

**Comment by Napster2210** [comment]
@apalasopoulos1986  Check version of `ngx-spinner` in your `package-lock.json` file. It should be `v10.0.1`.
