### ISSUE TITLE
'Property "type" is missed' warning, even for custom spinners

### ISSUE THREAD

**Issue by ac-ih** [Napster2210/ngx-spinner#249]
After upgrading from 12.x to 13.1.x, I am seeing the below warnings in the console when using custom spinners. (kind of related https://github.com/Napster2210/ngx-spinner/issues/222):

```
Property "type" is missed. Please, provide animation type to <ngx-spinner> component and ensure css is added to angular.json file
```

In https://github.com/Napster2210/ngx-spinner/issues/222, the solution is to add a global `type` -- which is added in 14.x, but I am not sure if it resolved the warnings for custom spinners. I am unable to upgrade to 14.x at the moment.

Custom spinners are used like so:

```
<ngx-spinner
  bdColor="rgba(0, 0, 0, 1)"
  template="<img src='https://media.giphy.com/media/o8igknyuKs6aY/giphy.gif' />"
>
</ngx-spinner>
```

So `type` property should not be required for custom spinners. Or if it's a big change, maybe `type` can be set to `custom`?

Could the warnings for custom spinners please be resolved in 13.1.2?

**Comment by Napster2210** [comment]
@ac-ih This has been fixed in v16. Could you please check and feel free to reopen if it still exists?
