### ISSUE TITLE
Ignore loading Bar in some backend calls

### ISSUE THREAD

**Issue by nishit-rspl** [Napster2210/ngx-spinner#25]
Need a new feature to ignore loading bar in some request, where response time is too less. 

Real case scenario : we make lookup service call to backed for drop downs, so when we edit a letter it again call the service an at times, response is quite fast this creates flashy screen and user experience is not ver good

**Comment by Napster2210** [comment]
@nishit-rspl added threshold in latest version so it won't be there anymore. Closing the issue as it's for older version.
