### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by tobysmith568** [Napster2210/ngx-spinner#250]
Hey :)

I can see that a license was added to the project in response to issue #65 however it seems that the license was never configured to be included in your npm package.

You can see in the "Code" view on npmjs.com there's no license file.
https://www.npmjs.com/package/ngx-spinner/v/15.0.1?activeTab=code

Please can you update your build/deploy process so that the file is included as a top-level file in the package?

This is important because your license (the MIT license) states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

However you yourselves don't include the license with that copy of the software.

This in turn makes it impossible for the consumers of your package to adhere to your license when using build automation tools (like the Angular CLI).

Thanks! :)

**Comment by Napster2210** [comment]
@tobysmith568 This has been fixed in v16. Could you please check and feel free to reopen if it still exists?

**Comment by tobysmith568** [comment]
Perfect, thanks :)

CC: @wcroteau
