### ISSUE TITLE
Spinner icon does not display for angular v15.2.0

### ISSUE THREAD

**Issue by joshualburke** [Napster2210/ngx-spinner#257]
Running ngx-spinner works for v15.0.1 but does not for v15.2.0. The icon is not displayed.

**Comment by sharath-mv** [comment]
Change type like this.
 NgxSpinnerModule.forRoot({ type: 'la-ball-scale-multiple' })

**Comment by tapvirvirk** [comment]
Any update on this issue?

**Comment by tapvirvirk** [comment]
Icon is not even showing on angular 16.

**Comment by Sparkmb21** [comment]
same issue on the Angular 14

**Comment by Napster2210** [comment]
@joshualburke @tapvirvirk @Sparkmb21 @frsimond Have you guys added css file in `angular.json` file as mentioned in the README: https://github.com/Napster2210/ngx-spinner#usage

**Comment by Napster2210** [comment]
Latest version v16 is now available.

**Comment by tapvirvirk** [comment]
@Napster2210 I did specify the css in angular but no luck. The spinner wheel is not displaying up on the screen. However if I switch to version 12.0.0 then wheel is showing up.

**Comment by Napster2210** [comment]
@tapvirvirk There is new version available v16.0.1. Can you please check the above issue with the latest version?

**Comment by tapvirvirk** [comment]
Yes, its working. Thanks

**Comment by PouryaMontakhab** [comment]
same issue with angular 16

**Comment by Napster2210** [comment]
@PouryaMontakhab Can you please replicate the issue in Stackblitz or Code Sandbox and share the url here?

**Comment by dupiesdupreez** [comment]
Also had this issue, solved it with adding the style.

` 
"styles": [ "node_modules/ngx-spinner/animations/ball-scale-multiple.css" , "node_modules/ngx-spinner/animations/square-jelly-box.css"],
`

```
 imports: [
    BrowserModule,
    RouterModule.forRoot(appRoutes, { initialNavigation: 'enabledBlocking' }),
    NgxSpinnerModule.forRoot({ type: 'square-jelly-box' }),
  ],
```

**Comment by miskozajac** [comment]
Why is this issue closed? those animations from load awesome are not working

**Comment by EugeneHermano** [comment]
It works after adding `provideSpinnerConfig({type: 'ball-spin-clockwise'}),` in the providers array of `appConfig` file. 
Note that `.forRoot()` is not working and NgModule is not default in angular app (at least in the current releases). Don't know why `provideSpinnerConfig` is not stated in the NgxSpinner documentation
