### ISSUE TITLE
Angular v16 support

### ISSUE THREAD

**Issue by DominicWrege** [Napster2210/ngx-spinner#258]
Any plans to support Angular v16?

**Comment by DominicWrege** [comment]
Temporary workaround [ngx-spinner16](https://www.npmjs.com/package/ngx-spinner16?activeTab=readme)

**Comment by Kirandeep1** [comment]
Is there a set date for the release of v16?

**Comment by kirandeepkaur13** [comment]
Is there a set date for the release of v16?

**Comment by Napster2210** [comment]
I'm planning for this week.

**Comment by DominicWrege** [comment]
Which icon is not visible ?

**Comment by shubhamraturi37** [comment]
when you are planning to support for angular 16?

**Comment by DominicWrege** [comment]
> I'm planning for this week.

https://github.com/Napster2210/ngx-spinner/issues/258#issuecomment-1554169286

**Comment by Napster2210** [comment]
It will be there by today or tomorrow.

**Comment by Napster2210** [comment]
@DominicWrege @tapvirvirk @shubhamraturi37 @kirandeepkaur13 @sfeilmeier  Latest version v16 is now available!

**Comment by kirandeepkaur13** [comment]
> @DominicWrege @tapvirvirk @shubhamraturi37 @kirandeepkaur13 @sfeilmeier  Latest version v16 is now available! 

@Napster2210 thanks for the update 👍.

**Comment by DominicWrege** [comment]
@Napster2210 can u take a look at that ? https://github.com/Napster2210/ngx-spinner/pull/261
