### ISSUE TITLE
Default visibility

### ISSUE THREAD

**Issue by jobam** [Napster2210/ngx-spinner#26]
Currently the spinner is disabled by default.
You have to call <spinnerService>.show() action to show it.
But, in some cases, the service injection is too long and i want to show the spinner during this loading time. 

**Add an optional attribute** to set the **default visibility** (at false by default).

Exemple
----------
```
<ngx-spinner bdColor="rgba(51, 51, 51, 0.8)" size="large" color="#fff" type="square-loader" loadingText="Loading app..." isVisibleByDefault="true"></ngx-spinner> ```

**Comment by Napster2210** [comment]
@jobam Is it feasible? Can you please explain your case in detail? It would be great if you can share your code snippet.
