### ISSUE TITLE
Standalone Support

### ISSUE THREAD

**Issue by DominicWrege** [Napster2210/ngx-spinner#267]
Is it possible to add standalone support? Angular will soon shift everything to standalone soon, it's the future.

**Comment by osamaawadalla** [comment]
+1

**Comment by Et3rnal** [comment]
+1

**Comment by Et3rnal** [comment]
+1

**Comment by Napster2210** [comment]
V17 is now available: https://www.npmjs.com/package/ngx-spinner/v/17.0.0

**Comment by DominicWrege** [comment]
Awesome awesome :+1:
