### ISSUE TITLE
Expression based show/hide instead of service based?

### ISSUE THREAD

**Issue by raydawg2000** [Napster2210/ngx-spinner#30]
Is it possible now, or in a future update, to have the ability to show/hide the spinner based on an expression evaluation instead of having to use the service?

Something like 

> pendingLoads: number = 0;
> <ngx-spinner [show]="pendingLoads > 0"></ngx-spinner>

So if it evals to true, then show otherwise hide.

Thanks
-Ray

**Comment by Napster2210** [comment]
@raydawg2000 Currently there is no plan like this, and also it's not a good practice.

**Comment by iamavieira** [comment]
You may call the show() on ngOnInit() and remove the spinner component from DOM at your will with *ngif.
