### ISSUE TITLE
Overlay covering only part of the screen

### ISSUE THREAD

**Issue by phoude** [Napster2210/ngx-spinner#31]
If the spinner is shown when at a bottom of a page then we only see part of it. It appears like the overlay will only cover the surface of the initial screen position. See https://stackblitz.com/edit/angular-9e6nmr

**Comment by Augustus-Gabe** [comment]
I've worked around this problem changing the position from absolute to fixed in the 
black- overlay class and placed it in my styles.css:

.black-overlay[_ngcontent-c5] {
    position: fixed !important;
}

This should be the default behaviour of the spinner overlay.

**Comment by danieldluyzo** [comment]
I tried this but it still covers only a part of the screen.
Any ideas ?

**Comment by danieldluyzo** [comment]
Sorry, I was adding it to the component's css. 

It does work on styles.css. 

Thanks!

**Comment by sbley** [comment]
```css
.black-overlay {
  position: fixed !important;
}
```
does fix the spinner position to be centered on the screen. However, the loading text is not part of `.black-overlay`. That's why the loading text is not centered.

Hence, the loading text should be rendered as a child of `.black-overlay`.

**Comment by romelgomez** [comment]
The simple spinner without custom settings.  

```
<ngx-spinner></ngx-spinner>
```

Place this code in the DOM: 

```
<div _ngcontent-nxh-c1="" class="overlay ng-star-inserted" ng-reflect-ng-style="[object Object]" style="background-color: rgba(51, 51, 51, 0.8); position: absolute;"><div _ngcontent-nxh-c1="" class="la-ball-scale-multiple la-3x" style="color: rgb(255, 255, 255);"><!--bindings={
  "ng-reflect-ng-for-of": "0,1,2"
}--><div _ngcontent-nxh-c1="" class="ng-star-inserted"></div><div _ngcontent-nxh-c1="" class="ng-star-inserted"></div><div _ngcontent-nxh-c1="" class="ng-star-inserted"></div></div><div _ngcontent-nxh-c1="" class="loading-text"></div></div>
```

It's already has hardcoded set `position: absolute;` which rewrites position of  `.overlay` styles.


```
.overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 99999!important;
}   
```

Notes:
- In large views the overlay only cover the half of the view. 
- It work the first time, the second time is not.
