### ISSUE TITLE
Using into http interceptors

### ISSUE THREAD

**Issue by pairmix** [Napster2210/ngx-spinner#32]
Hi there,
I don't know how to use it with interceptor.
Spinner never appears.

app.module.ts
````
import { NgxSpinnerModule } from 'ngx-spinner';

imports: [
    ...
    NgxSpinnerModule,
    ...
]
````

interceptor.ts
````
import { NgxSpinnerService } from 'ngx-spinner';
export class LoadingInterceptor implements HttpInterceptor {
constructor(private spinner: NgxSpinnerService) { }

intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        /** spinner starts on init */
        this.spinner.show();
        return next.handle(req).do((event: HttpEvent<any>) => {
            /** spinner ends */
            this.spinner.hide();
        }, (err: any) => {
            /** spinner ends */
            this.spinner.hide();
        });        
    }
````

app.html:
````
<ion-nav [root]="rootPage" #content swipe-back-enabled="false"></ion-nav>
<ngx-spinner></ngx-spinner>
````

**Comment by pavan6cs** [comment]
any update how can we use the spinner in error handle service .in my case i opened spinner in one home.component, when server error occurs im trying to hide spinner from app.component.ts.but it not working

**Comment by segux** [comment]
Did you check if is creating more than one instance of singleton NgxSpinnerService?

**Comment by ddanilovich** [comment]
It's look like next.handle(req) immediately emit an event and your spinner is closed. At least I had such a problem. Try this:

```typescript
return next.handle(req).do((event: HttpEvent<any>) => {
  /** spinner ends */
  if (event instanceof HttpResponse) {
    this.spinner.hide();
  }
}
```

**Comment by khalilTN** [comment]
@ddanilovich did your sample work ? I'm facing the same problem.
The call of hide and show should be centralized

**Comment by ddanilovich** [comment]
@khalilTN , I actually use something like this (almost the same as the previous example):

```typescript
function intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
  // show spinner

  return next.handle(req).pipe(
    tap(
      (evt: HttpEvent<any>) => {
        if (!(evt instanceof HttpResponse)) {
          return;
        }

        // hide spinner
      },
      (error: Error) => {
        // hide spinner
      }
    )
  );
}
```

**Comment by karincayazilim** [comment]
Is there any bi solution found?

**Comment by aqib204** [comment]
Instructions are not clear. Can someone please come up with a solution.?

**Comment by willyt150** [comment]
We've wrapped the NgxSpinnerService inside a separate service that allows multiple things to say that we're busy and not hide the spinner until all of them say idle.
``` ts
export class BusyService {
  private busyRequestCount = 0;
  constructor(private spinnerService: NgxSpinnerService) { }

  public busy() {
    this.busyRequestCount++;
    this.spinnerService.show();
  }

  public idle() {
    this.busyRequestCount--;
    if (this.busyRequestCount <= 0) {
      this.busyRequestCount = 0;
      this.spinnerService.hide();
    }
  }
}
```

Then in the interceptor, it's exactly like @ddanilovich's [example](https://github.com/Napster2210/ngx-spinner/issues/32#issuecomment-447286099), we just pipe to finalize instead of tap. And you can further enhance your interceptor to check for headers if you want to possibly NOT show the busy indicator for some http calls.

``` ts
export class LoaderInterceptor implements HttpInterceptor {

  constructor(private busyService: BusyService) { }
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.busyService.busy();
    return next.handle(req).pipe(
      finalize(() => {
        this.busyService.idle();
      })
    );
  }
}
```

The BusyService isn't necessary and you can just replace it with the NgxSpinnerService

**Comment by venkatramarajup** [comment]
@pairmix hi i am facing the same issue as ur's, did you get any solution ??

**Comment by pairmix** [comment]
@venkatramarajup i gave up this tool.
You can try this: https://material.angular.io/components/progress-spinner/overview

**Comment by venkatramarajup** [comment]
for angular component  spinner you can look at here https://www.angularjswiki.com/angular/creating-progress-spinner-in-angular/
