### ISSUE TITLE
Unable to launch my app after adding NgxSpinner

### ISSUE THREAD

**Issue by ghassen1khalil** [Napster2210/ngx-spinner#33]
I installed the dependency and added NgxSpinnerModule to AppModule as decsribed in the guide but when I launch my application using npm start I get following error
<img width="635" alt="capture d ecran 2018-08-25 a 18 51 05" src="https://user-images.githubusercontent.com/2848689/44620619-dc0a7100-a897-11e8-99a8-eca82f237464.png">

**Comment by Napster2210** [comment]
Can you please post your `package.json`?

**Comment by ghassen1khalil** [comment]
Here it is : 
```
{
  "name": "flad-frontend",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.1.4",
    "@angular/common": "6.1.4",
    "@angular/compiler": "6.1.4",
    "@angular/core": "6.1.4",
    "@angular/forms": "6.1.4",
    "@angular/http": "6.1.4",
    "@angular/platform-browser": "6.1.4",
    "@angular/platform-browser-dynamic": "6.1.4",
    "@angular/router": "6.1.4",
    "@ng-idle/core": "^2.0.0-beta.15",
    "@ng-idle/keepalive": "^2.0.0-beta.15",
    "angular-sweetalert-service": "^2.0.2",
    "angular2-jwt": "^0.2.3",
    "angular2-moment": "^1.9.0",
    "bootbox": "^4.4.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery-confirm": "^3.3.2",
    "ngx-pagination": "^3.1.0",
    "ngx-spinner": "^6.1.2",
    "rxjs": "^6.2.2",
    "sweetalert": "^2.1.0",
    "tslib": "^1.9.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.1.5",
    "@angular/compiler-cli": "6.1.4",
    "@angular/language-service": "6.1.4",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.9.2"
  }
}
```

**Comment by Napster2210** [comment]
Package.json seems perfect, but I think it's due to any of the dependencies because I haven't use `Object(...)` in my code

**Comment by Napster2210** [comment]
It would be better if you can create `plunker` or any other similar

**Comment by ghassen1khalil** [comment]
It's a bit complicated for me to go on plunker, If you want I can give you access to my bitbucket project :)

**Comment by Napster2210** [comment]
Okay that would be better

**Comment by abdulbarik** [comment]
Any update on it, I am also getting same issue

**Comment by Napster2210** [comment]
@ghassen1khalil I have sent you a mail please check it out.

**Comment by manish-devon** [comment]
@Napster2210 is this solved yet? it's bugging my code too

**Comment by manish-devon** [comment]
@ghassen1khalil did you get your code working ? @Napster2210 any update ?

**Comment by dayaki** [comment]
Am getting this error too. @Napster2210 @ghassen1khalil  any update? are you able to solve this?

**Comment by oleksii-pimenov** [comment]
Same error, any updates? @Napster2210 @ghassen1khalil

**Comment by Napster2210** [comment]
@ghassen1khalil @abdulbarik @manish-devon @dayaki @oleksii-pimenov For above issue you can refer this link: https://stackoverflow.com/questions/50374194/error-typeerror-object-is-not-a-function-using-angularfirestore-and-fire
It's not about `ngx-spinner` but issue is same.

**Comment by Napster2210** [comment]
Let me if this would help for you guys.

**Comment by dayaki** [comment]
@Napster2210 followed the instructions contained in the link above, it all seem to be related to firebase and am not using firebase. Still facing same issue

**Comment by kritisharmaa01** [comment]
Please tell me also the solution. I'm tired of searching! @Napster2210 @ghassen1khalil . thanks in advance :)

**Comment by Napster2210** [comment]
@kritisharmaa01 Let me know your Angular & `ngx-spinner` versions?
