### ISSUE TITLE
Changing style after first use

### ISSUE THREAD

**Issue by caioladislau** [Napster2210/ngx-spinner#34]
Hi!

I want to use the spinner (ngx-spinner v6.1.2 - [see](https://www.npmjs.com/package/ngx-spinner)) on a custom style on the **first loading** (loading my app first time). After this, I want use the same spinner on a **different style** (app is loaded, but I'm loading some data while I use the app).

Someone did it before? Some tip about the best way to do this?

I'm using Angular 6 on asp.net core.

--
Stackoverflow question: [https://stackoverflow.com/q/52079478/3783143](https://stackoverflow.com/q/52079478/3783143)

**Comment by Napster2210** [comment]
Currently there is no such kind of functionality available, if in future there is some plan like this will surely let you know.
Thanks.
