### ISSUE TITLE
How to change position of spinner/loader?

### ISSUE THREAD

**Issue by akki543** [Napster2210/ngx-spinner#35]
I have a page with a scroll-bar , so loader type is right at the bottom of the screen , how can i make it center aligned ?
I'm using spinner with angular 6.

**Comment by shankesgk2** [comment]
`.black-overlay` `position` should be `fixed`
![1536134744048](https://user-images.githubusercontent.com/8123290/45079707-cca3e700-b125-11e8-9da6-bf5190378cd9.jpg)

**Comment by Napster2210** [comment]
@akki543 @shankesgk2 You can overwrite `.black-overlay` in your `style.css`
