### ISSUE TITLE
Not showing in Angular 6.1.3

### ISSUE THREAD

**Issue by alpeshvasani** [Napster2210/ngx-spinner#38]
I am trying to use it in my Angular 6.1.3 project..but it is not showing with no errors.

**Comment by aderenzis** [comment]
Try adding NgxSpinnerService to the providers in app.module.ts.

**Comment by Napster2210** [comment]
@alpeshvasani can you please share your code snippet or `stackblitz` url for better understanding?

**Comment by aderenzis** [comment]
I'm using angular 7.0.0 and it works. 

Version in package.json:     "ngx-spinner": "^6.1.2"

Html example

` <ngx-spinner
    bdColor = ""
    size = "default"
    color = "#ee7d06"
    type = "ball-8bits"
  >
    <p class="py-3" style="font-size: 20px; color: white">Searching for a rival...</p>
  </ngx-spinner>

<button (click) ="show()"> Show </button>
<button (click) ="hide()"> Hide </button>

`


Ts example

` 
import { NgxSpinnerService } from 'ngx-spinner';

constructor(
   private spinner: NgxSpinnerService
   ) {
   
  }

 show() {
    this.spinner.show();
  }

 hide() {
    this.spinner.hide();
  }`

**Comment by alpeshvasani** [comment]
@aderenzis  It worked.

**Comment by amjadyahya** [comment]
My  configuration was wrong, it works now.

**Comment by aderenzis** [comment]
Nice. Glad that works!

**Comment by rspl-yuvraj** [comment]
Thanx @aderenzis
