### ISSUE TITLE
spinner not working in IE. and am using angular 6

### ISSUE THREAD

**Issue by m1a2n3o4** [Napster2210/ngx-spinner#39]
`ngx-spinner` is a custom element, so in this case, if you add `<ngx-spinner>` in your HTML file then you have to add **CUSTOM_ELEMENTS_SCHEMA** to your app module.

```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

// ........

@NgModule({
// ...
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
]
})
```

**Comment by cyberundertakor** [comment]
Change this in package.json

    "ngx-spinner": "6.0.0",

**Comment by Napster2210** [comment]
@m1a2n3o4 is it working for you now?
