### ISSUE TITLE
Feature Request: Only cover certain element

### ISSUE THREAD

**Issue by davidfindlay** [Napster2210/ngx-spinner#42]
It'd be great if there were a way to set the ngx-spinner to only cover a table that's loading for instance, rather than the whole page. If there isn't a way to do this now, could this please be added in the future?Thanks,

David

**Comment by Napster2210** [comment]
@davidfindlay have you tried to put `ngx-spinner` element in your table wrapper instead of `app.component.html`?

**Comment by pmeems** [comment]
I've got a similar question. I have a mat-card and the mat-content is retrieved from another REST, so it takes a few seconds before the data is shown.
It would be great if I could show one of your great spinners in the meantime.

On startup I also use your spinner, which works fine.

My code so far:
```
<mat-card
  *ngIf="!hideCard"
  id="chart-card">
  <mat-card-header>
    <mat-card-title>{{name}}
      <button type="button" class="close" aria-label="Close" (click)="hideCard=true">
        <span aria-hidden="true">&times;</span>
      </button>
    </mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <div
      <google-chart
        *ngIf="!chartLoading"
        #chart
        [title]="'Test Bar chart'"
        [type]="'AreaChart'"
        [data]="myData"
        [columnNames]="myColumnNames"
        [options]="optionsStacked">
      </google-chart>
    <ngx-spinner
      bdColor="rgba(51, 51, 51, 0.8)"
      size="medium"
      color="#fff"
      type="ball-spin-clockwise-fade-rotating">
    </ngx-spinner>
    </div>
  </mat-card-content>
</mat-card>
```

**Comment by rspl-yuvraj** [comment]
@pmeems I'm working on multiple spinner support will be available in v7.
