### ISSUE TITLE
i0.defineInjectable is not a function

### ISSUE THREAD

**Issue by VSKerberos** [Napster2210/ngx-spinner#43]
I have a problem with spinner I have downloaded the package and implemented as shown below. But I get an error any help please.

Thanks.

![image](https://user-images.githubusercontent.com/13761813/46766070-8aa02f00-cce9-11e8-9a15-4bc8471b605b.png)

```
In Module
import { NgxSpinnerModule } from 'ngx-spinner';

// ........

@NgModule({
// ...
  imports: [
  NgxSpinnerModule
]
})

In Component
import { NgxSpinnerService } from 'ngx-spinner';

```
package.json

"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@toverux/ngx-sweetalert2": "^4.0.0",
    "angular-imask": "1.0.2",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "imask": "^4.0.0",
    "jquery": "3.1.1",
    "ngx-currency": "^1.5.0",
    "ngx-spinner": "^6.1.2", 
    "perfect-scrollbar": "^1.4.0",
    "rimraf": "^2.6.2",
    "rxjs": "^5.5.11",
    "rxjs-es": "^5.0.0-beta.12",
    "rxjs-system-bundle": "^5.1.1-2",
    "sweetalert2": "^7.26.23",
    "systemjs": "^0.20.9",
    "tiny-date-picker": "^3.2.6",
    "tippy.js": "^3.0.4",
    "zone.js": "^0.7.7"
  },

**Comment by Napster2210** [comment]
@VSKerberos why error shows `....../scripts/ngx-spinner.umd.js` it should be in `node_modules` rather than in `scripts` folder. And also you're using angular 5 and the version of `ngx-spinner` is compatible with angular 6.

**Comment by VSKerberos** [comment]
@Napster2210 thank you for your answer, in system-config config file I mapped the scripts folder. It's also available in node_modules but it seems that main reason is you mentioned that Angular versions.

**Comment by VSKerberos** [comment]
I have installed the specific version of package which is suitable with Angular 5 it resolves the problem.
Thanks.
npm install ngx-spinner@2.0.0
