### ISSUE TITLE
Angular 7 support ?

### ISSUE THREAD

**Issue by opunbuds** [Napster2210/ngx-spinner#45]
Just wondering if ngx-spinner is suport on angular 7 or not

**Comment by marie-dk** [comment]
I just upgraded my project from Angular 6 to 7 today, and it seems to work fine :-)

**Comment by Ardenexal** [comment]
the `package.json` file needs updating to remove the warning when doing a `npm install`

**Comment by rspl-yuvraj** [comment]
@opunbuds There are no such changes in Angular v7 that affects my module, so you can use the latest version `6.1.2`.
Make sure you're using proper update guide:
https://update.angular.io/

**Comment by l4cr0ss** [comment]
Echoing @Ardenexal please update the package.json file to remove the dependency warnings

**Comment by romelgomez** [comment]
![screenshot from 2018-11-19 11-39-59](https://user-images.githubusercontent.com/2358251/48721515-14e48880-ebf0-11e8-95ec-142333660a3b.png)

Please update the package.json file
