### ISSUE TITLE
Use as loader

### ISSUE THREAD

**Issue by pantonis** [Napster2210/ngx-spinner#49]
Hi,

Is it possible to use this as a loader for a specific section of my page (e.g table loading) and not the entire page which blocks?

Thanks

**Comment by Napster2210** [comment]
@pantonis Will be resolved in **v7.0.0**

**Comment by Napster2210** [comment]
@pantonis Please check with the latest release [v7.0.0](https://github.com/Napster2210/ngx-spinner/tree/v7.0.0)
