### ISSUE TITLE
Disable full screen

### ISSUE THREAD

**Issue by enniob** [Napster2210/ngx-spinner#5]
I was planning on using the spinner inside a div and when I add it to my component it goes on full screen. I wounder if its possible to give an option to be full screen or not, and if you select not the spinner would display inside your div.

**Comment by rspl-yuvraj** [comment]
Thanx for using `ngx-spinner` @enniob , I'll add this feature in my next release. Thanx for your suggestion.

**Comment by enniob** [comment]
Thanks for the reply @rspl-yuvraj  do you have an idea when would be the next realease? 👍

**Comment by Napster2210** [comment]
@enniob  I'm planning for next release on or before next Friday.

**Comment by Napster2210** [comment]
@enniob Working on it will release as soon as possible.

**Comment by enniob** [comment]
Cool thanks for the update.

**Comment by byhoratiss** [comment]
Any updates on this issue? This is the only issue that does not allow me to use this awesome spinner.

**Comment by rspl-yuvraj** [comment]
@enniob @ChristianHardy @byhoratiss I'm going to start work on this in next few days due to the busy schedule. Will let you know guys once I have done.

**Comment by marie-dk** [comment]
I use this workaround for now:
```
.black-overlay {
    position:absolute !important;
}
```
This way the spinner will only fill the DOM element you put it in.

**Comment by Napster2210** [comment]
@enniob @ChristianHardy @byhoratiss @marie-dk This has been resolved and will be available in the current release([v6.1.1](https://github.com/Napster2210/ngx-spinner/releases/tag/v6.1.1))

**Comment by shree-houseology** [comment]
Can we get this feature for angular 5 version?

**Comment by Ankit-Anchan** [comment]
How to use this feature? Cannot find anything related to it in the documentation.

**Comment by saeidzebardast** [comment]
How can I use it? There is nothing in the documentation.

**Comment by Ankit-Anchan** [comment]
> > How to use this feature? Cannot find anything related to it in the documentation.
> 
> Hi, found the link yet? Can't find one either

I have not.

**Comment by pedroolimpio** [comment]
For me it works like this:

```
.black-overlay {
    position:fixed !important;
}
```

**Comment by michael-mckenna** [comment]
Disabling still does not work for me, using 7.0.
