### ISSUE TITLE
how to apply ngx-spinner to whole html page from another ts file

### ISSUE THREAD

**Issue by akshaybhagwat76** [Napster2210/ngx-spinner#50]

**Comment by goel-sunny** [comment]
Define the component in the app-component i.e. root component , and use it where ever you want to use just by injecting the **NgxSpinnerService** service.

**Comment by sahanaprao** [comment]
Define Utils class file which will have **NgxSpinnerService** service injector. So create one function in Utils class for showing Spinner and another function for hide Spinner. Just call the respective Utils function of spinner wherever you want it.

**Comment by Napster2210** [comment]
@akshaybhagwat76 @goel-sunny @sahanaprao Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4.
