### ISSUE TITLE
Use an image for spinner

### ISSUE THREAD

**Issue by BruneXX** [Napster2210/ngx-spinner#54]
Hi, Like as enhancement, will be great if we can add a custom gif image or icon to use for spinner.

**Comment by alactic** [comment]
@BruneXX is right, please can we have this enhancement?

**Comment by ashokv7s** [comment]
@BruneXX @alactic true! please!! this would be greatly helpful or if anyone knows to add assets/images to angular library ?

**Comment by Napster2210** [comment]
@BruneXX @alactic @ashokv7s Thanx for suggestion, will work on this soon. Currently working on new release **v7.0.0**

**Comment by enniob** [comment]
@Napster2210 any update on this?

**Comment by Napster2210** [comment]
@enniob I'm planning this in my next release.

**Comment by prasanna-5796** [comment]
@Napster2210, can you let us know when will the next release, containing this enhancement be?

**Comment by rspl-yuvraj** [comment]
@BruneXX @alactic @ashokv7s @enniob @prasanna-5796 This functionality is already being done and will be available with `v9.0`

**Comment by Napster2210** [comment]
@BruneXX @alactic @ashokv7s @enniob @prasanna-5796  Latest version is published which has image support [v9](https://github.com/Napster2210/ngx-spinner/releases/tag/v9.0)
You can also check details on npm [ngx-spinner](https://www.npmjs.com/package/ngx-spinner)
