### ISSUE TITLE
waring  in defineInjectable

### ISSUE THREAD

**Issue by thangaprakashari** [Napster2210/ngx-spinner#55]
WARNING in ./node_modules/ngx-spinner/fesm5/ngx-spinner.js
69:59-75 "export 'defineInjectable' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors

**Comment by Napster2210** [comment]
@thangaprakashari @madhuri03 Please check with the latest release [v7.0.0](https://github.com/Napster2210/ngx-spinner/tree/v7.0.0)

**Comment by madhuri03** [comment]
@Napster2210 Still getting the warning with V7.0.0. I am using angular V5.2.0.
My issue is gone by using ngx-spinner v2.0.0.

**Comment by Napster2210** [comment]
Yes, beacuse as I mentioned in README if you're using Angular 5.2 then you
should use v2.0.0
