### ISSUE TITLE
Need Spinner With Close button At Top Right

### ISSUE THREAD

**Issue by dpwadewilson** [Napster2210/ngx-spinner#57]
Need a close button at that top-right for close button over black-overlay.

**Comment by AntoineJeanDev** [comment]
You can just add a button with (click) attribute right ?

**Comment by Napster2210** [comment]
@dpwadewilson Yes, you can a button on top of spinner overlay and handle the hide/show method of spinner on click of that button. Thanx @AntoineJeanDev
