### ISSUE TITLE
How to put spinner in button?

### ISSUE THREAD

**Issue by gab-palmeri** [Napster2210/ngx-spinner#58]
Hi, I would like to put the spinner in a button, or in a custom position (for example inside a div, ecc). I've tried putting the <ngx-spinner></ngx-spinner> inside my button, but it's still displaying on the center of the page, even with the fullScreen="false". How can I achieve this?

**Comment by Napster2210** [comment]
@gab-palmeri Can you please post your HTML code along with its CSS classes?

**Comment by gab-palmeri** [comment]
I don't know if it's relevant, I just put your custom tag inside a button and then calles the .show() method, i haven't applied any relevant css to it

**Comment by rspl-yuvraj** [comment]
@gab-palmeri Can you please put the spinner in one div with specific height and width just to check?
