### ISSUE TITLE
Using fullscreen=false fits whole module instead of parent div

### ISSUE THREAD

**Issue by PaoloneM** [Napster2210/ngx-spinner#59]
Ngx-spinner Version 7.0.0
Angular version: 7.2.2

Code in component template:
```
<div *ngIf="!formActive">{{jsonFormStatusMessage}}
<ngx-spinner
    bdOpacity = 0.9
    bdColor = "#333"
    size = "default"
    color = "#fff"
    type = "ball-pulse"
    fullScreen = "false"
    >
    <p style="color: white" > Loading... </p>
</ngx-spinner>
</div>
```

Expected behavior: spinner covering only the div containing my component.

Effective behavior: spinner covers the whole root module.

**Comment by Napster2210** [comment]
@PaoloneM Try to set fixed height and width to your div and check it again.

**Comment by PaoloneM** [comment]
@Napster2210 thanks for your quick reply, I update my code setting fix height and width:
```
<div *ngIf="!formActive" style="height: 50px; width: 500px;">
  {{jsonFormStatusMessage}}
  <ngx-spinner
    bdOpacity = 0.9
    bdColor = "#333"
    size = "default"
    color = "#fff"
    type = "ball-pulse"
    fullScreen = "false"
    >
    <p style="color: white" > Loading... </p>
  </ngx-spinner>
</div>
```
but the behavior doesn't change.

**Comment by Napster2210** [comment]
@PaoloneM That's weird, in my demo website it's working fine with that property. I'll find a workaround of this issue. As of now, just put below class to your CSS file:
`:host ::ng-deep .black-overlay{
  position: relative !important;
}`
which will fix your issue. (Dirty Hack!!!!!)

**Note:** You have to use `fullScreen` as `[fullScreen]="false"` as it's boolean not string.

```
<div *ngIf="!formActive" style="height: 50px; width: 500px;">
  {{jsonFormStatusMessage}}
  <ngx-spinner
    bdOpacity = 0.9
    bdColor = "#333"
    size = "default"
    color = "#fff"
    type = "ball-pulse"
    [fullScreen] = "false"
    >
    <p style="color: white" > Loading... </p>
  </ngx-spinner>
</div>
```

**Comment by PaoloneM** [comment]
> **Note:** You have to use `fullScreen` as `[fullScreen]="false"` as it's boolean not string.

This fixes it at all. No need to put div size or CSS hack. 

My code above is derived from your live demo site "black div" where is shown the code of the config you select. There, the "fullscreen" setting is shown without square braces. Might be that it's a small documentation bug.

Thanks alot for your support.

**Comment by michael-mckenna** [comment]
@Napster2210 I copied your solution but to no avail. I even tried the dirty hack and my spinner was still full screen. If I set these values in developer tools it works, but I can't get fullScreen="false" to ever work in my project.

Developer Tools
```
element.style {
    background-color: rgba(0, 0, 0, 0);
    position: static; // Changes this from relative to static
}
.black-overlay[_ngcontent-c13] {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 99999!important;
}
```

**Comment by michael-mckenna** [comment]
After an hour of debugging I figured it out right after sending that lol! I just took the ngx spinner out of the div it was in.
