### ISSUE TITLE
'ngx-spinner' is not a known element

### ISSUE THREAD

**Issue by ladkatprashant55** [Napster2210/ngx-spinner#6]

**Comment by weijyewang** [comment]
Hi @ladkatprashant55  i got the same error, how did u resolve it?

**Comment by Napster2210** [comment]
@weijyewang `ngx-spinner` is a custom element, so in this case, if you add `<ngx-spinner>` in your HTML file then you have to add `**CUSTOM_ELEMENTS_SCHEMA**` to your app module.

`
import { NgModule, **CUSTOM_ELEMENTS_SCHEMA** } from '@angular/core';
-
-
-
@NgModule({
// ...
  **schemas: [
    CUSTOM_ELEMENTS_SCHEMA
]**
})
`

**Comment by ladkatprashant55** [comment]
no I have used another spinner component

**Comment by lvndry** [comment]
> @weijyewang `ngx-spinner` is a custom element, so in this case, if you add `<ngx-spinner>` in your HTML file then you have to add `**CUSTOM_ELEMENTS_SCHEMA**` to your app module.
> 
> ```
> import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
> 
> // ........
> 
> @NgModule({
> // ...
>   schemas: [
>     CUSTOM_ELEMENTS_SCHEMA
> ]
> })
> ```

It does't work
You should update your documentation

**Comment by sampladoc** [comment]
You need to follow the same installation guide you did for app.module in the page.module

**Comment by JigneshPatel04** [comment]
you used **shared.module.ts** then  used below code
import { NgxSpinnerModule } from 'ngx-spinner';

imports:[NgxSpinnerModule ]
exports:[NgxSpinnerModule ]

**Comment by AdedejiAdelanwa** [comment]
> I had the same issue, putting
> `schemas: [ CUSTOM_ELEMENTS_SCHEMA ]`
> in the app.module didn't fix it.
> 
> The error was resolved by adding
> `import { NgxSpinnerModule } from 'ngx-spinner';`
> and including `NgxSpinnerModule` in the NgModule
> in each modules the library was used

Hi @kunleawotunbo  I tried this and didn't work, can you be more explicit as to where to add the codes above. Thank you

**Comment by mavzerbay** [comment]
> @weijyewang `ngx-spinner` is a custom element, so in this case, if you add `<ngx-spinner>` in your HTML file then you have to add `**CUSTOM_ELEMENTS_SCHEMA**` to your app module.
> 
> ```
> import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
> 
> // ........
> 
> @NgModule({
> // ...
>   schemas: [
>     CUSTOM_ELEMENTS_SCHEMA
> ]
> })
> ```

It works ty

**Comment by EgoistDeveloper** [comment]
@JigneshPatel04's solution not work. Actually everything's fine but I realised forgot declaring my component in child module. In this case might helps.

```
@NgModule({
  declarations: [
    MyComponent // <-- but this part missing
  ],
  imports: [
    CommonModule,
    SharedModule, // NgxSpinnerModule imported here
    ChildRoutingModule,
  ],
  exports:[...],
  providers: [...]
})
export class ChildModule {}
```

And another strange thing is if this case happens all ngx-spinner parts shows this error in console.

**Comment by sajjadah964** [comment]
I have used all of this query but error occure in html file

**Comment by madmacc** [comment]
Tried all the above suggestion's in a new Angular 16 project and no luck.
Only has the app.module.ts and app.routing.module.ts no other modules just components.
