### ISSUE TITLE
Separate spinners (distinct by ref)

### ISSUE THREAD

**Issue by akash-potdar7** [Napster2210/ngx-spinner#60]
Usecase:
Currently most of us are using the spinner as a global spinner.
I want to use a spinner for certain scenarios, in various places, this spinner could be partly(in a card) used or fully, this is what the fullscreen is for.
Lets say the spinner service takes an argument id to trigger a desired spinner.

But the fullscreen is available on higher versions which aren't supported to angular 5

**Comment by Napster2210** [comment]
@akash-potdar7 I've to work on backward support for latest features.

**Comment by Napster2210** [comment]
@akash-potdar7 Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4. That may resolved your issue.

**Comment by akash-potdar7** [comment]
Yeah.. Thank you so much
