### ISSUE TITLE
Loading icon top 60%

### ISSUE THREAD

**Issue by dfilho** [Napster2210/ngx-spinner#61]
Well, I need to set the top attr of .loading-text css class to 50% but if I try this in my code, this don't change. Could you help me to do this?

Sorry for the english

**Comment by Napster2210** [comment]
Have you tried to overwrite `.loading-text` class in your main css file(style.css maybe) using `::ng-deep`?

**Comment by Napster2210** [comment]
@dfilho Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4. That resolves your issue.
