### ISSUE TITLE
Spinner backoverlay does not show on full screen on vertical scroll/modal

### ISSUE THREAD

**Issue by mchint01** [Napster2210/ngx-spinner#62]
Spinner backoverlay is not showing on full screen when page is vertically scrollable or has modals.

<ngx-spinner
  bdColor="rgba(222,223,215,0.8)"
  size="medium"
  color="#15135d"
  type="ball-atom"
  fullScreen="true"
></ngx-spinner>

How could we make spinner back overlay to show on entire page even when scrolled.

**Comment by bharat-dpd** [comment]
any solution? I am facing the same issue

**Comment by umahesh98** [comment]
I am also facing the same issue if i have more scroll able then the spinner is not covering entire screen
below link shows the exact issue 
https://ngx-spinner-demo-3xerm6.stackblitz.io

**Comment by bharat-dpd** [comment]
@umahesh98 
I solved the same problem by using the latest version 

> 7.0.0

with [fullScreen]="true"

**Comment by mchint01** [comment]
@bharat-dpd 
Yes updating to version 7 fixed it. marking this ticket as closed.
