### ISSUE TITLE
with div of *ngIf is not working

### ISSUE THREAD

**Issue by Bhuvn12** [Napster2210/ngx-spinner#64]
I am new in angular and using ngx-sppiner for waiting. I am using this inside *ngIf block then it is not working.

**Comment by Napster2210** [comment]
@Bhuvn12 Why you're using spinner inside `*ngIf` block? Can you please share your block of code with some details.

**Comment by Bhuvn12** [comment]
> @Bhuvn12 Why you're using spinner inside `*ngIf` block? Can you please share your block of code with some details.

thanks you so much for showing interest but i resolved my problem already. i got my it. but if you still want to give me answer then tell me that why ngx-spinner is not working inside *ngIf. ? this is matter why am i using inside *ngIf? well thanks you again for response.

**Comment by Napster2210** [comment]
*ngIf won't render component in DOM unless and until your condition becomes
true. So when you call `this.spinner.show()` method from component,
`ngx-spinner` component should be rendered before that.

**Comment by Napster2210** [comment]
@Bhuvn12 @Dk-Raziel Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4.

**Comment by brunano21** [comment]
@Napster2210 I checked version 7.1.14 but I don't see a way to show/hide the spinner via template only, as @Dk-Raziel wanted (within a `*ngIf` block)
