### ISSUE TITLE
Promisify show and hide commands on service

### ISSUE THREAD

**Issue by jpike88** [Napster2210/ngx-spinner#66]
Would be nice for smoother modal transitions if show and hide are promises. Right now they aren't and if I try to show a mat-dialog too early after calling hide(), it glitches out for a split second and doesn't look good. Still works though

**Comment by Napster2210** [comment]
@jpike88 Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4. That resolves your issue.
