### ISSUE TITLE
Unable to change opacity of inner elements

### ISSUE THREAD

**Issue by emeacham** [Napster2210/ngx-spinner#7]
Can you move the opacity setting to another element? The way the template is structured currently prevents the ability to fully override the default styling. The parent container forces inheritance of the opacity, and there isn't a way to change that with CSS alone.

**Comment by Napster2210** [comment]
Why do you want to change opacity of inner elements? What's your requirement?

**Comment by Napster2210** [comment]
Will try to figure it out and release it as soon as possible.

**Comment by rspl-yuvraj** [comment]
@dgpuranik demo still uses the older version of spinner. I'll update the demo in next 2 days. Will update the same on npm page.

**Comment by Napster2210** [comment]
@dgpuranik I have updated the demo as well as NPM page.
