### ISSUE TITLE
Spinner doesn't fit parent div

### ISSUE THREAD

**Issue by michael-mckenna** [Napster2210/ngx-spinner#71]
I checked out #59 and I'm still getting the error. I commented on it when I thought I got it working but turns out I didn't (so I'm making this issue). 

I have linked my Stackblitz below. I am setting `[fullScreen]="false"`, so not sure what the issue is.
https://stackblitz.com/edit/ngx-spinner-demo-djzvfr

**Comment by redo-X** [comment]
I have the same problem. Did some research and found out that the `position: fixed` is a problem here.

```
<ngx-spinner _ngcontent-c2="" bdopacity="0" color="#ffffff" fullscreen="false" size="small" type="ball-8bits"
    _nghost-c3="" ng-reflect-size="small" ng-reflect-color="#ffffff" ng-reflect-type="ball-8bits"
    ng-reflect-full-screen="false">
    <div _ngcontent-c3="" class="black-overlay" ng-reflect-ng-style="[object Object]"
        style="background-color: rgba(51, 51, 51, 0.8); **position: absolute;**">
        <div _ngcontent-c3="" class="la-ball-8bits la-sm" style="color: rgb(255, 255, 255);">
            ...
        </div>
        <div _ngcontent-c3="" class="loading-text"></div>
    </div>
</ngx-spinner>
```

If I change the `position: fixed` to `position: absolute`, it works as expected.

**Comment by Napster2210** [comment]
@michael-mckenna @redo-X Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4

**Comment by Napster2210** [comment]
@michael-mckenna Your parent div should have `position: relative;`

**Comment by Napster2210** [comment]
@michael-mckenna I have updated your StackBlitz check this out: https://stackblitz.com/edit/ngx-spinner-demo-sip2tq

**Comment by redo-X** [comment]
Thanks mate! @Napster2210
