### ISSUE TITLE
.show does not accept params

### ISSUE THREAD

**Issue by benjaminvazquez** [Napster2210/ngx-spinner#72]
I'm trying to use two insances of `ngx-spinner` but `this.show()` method expects 0 params. 

This is what I'm trying to do: 
```js
this.spinner.show('mySpinner', {
  type: 'line-scale-party', 
  size: 'large', 
  bdColor: 'rgba(100,149,237, .8)', 
  color: 'white'
});
```

**Comment by Napster2210** [comment]
@benjaminvazquez Check it out latest version: https://www.npmjs.com/package/ngx-spinner/v/7.1.4
You can also find working examples in README.

**Comment by Napster2210** [comment]
@benjaminvazquez Refer this: https://stackblitz.com/edit/angular-exgxk2
