### ISSUE TITLE
Allow background to fade in/out

### ISSUE THREAD

**Issue by jpike88** [Napster2210/ngx-spinner#73]
The background shows without animation, it's jarring.. should be a way to configure fade animation with seconds to fade

**Comment by dkruchok** [comment]
Plz)
Add some smooth animation to show/hide the spinner and background)

**Comment by nadav96** [comment]
No need for additions in the package, you can take advantage of Angular animations to achieve the desired behaviour:

```html
<ngx-spinner [@fadeIn]="loadingState" type="ball-elastic-dots">
</ngx-spinner>
```
```typescript
  loadingState = "in"

  async ngOnInit() {
    someWork()
    this.loadingState = "out"
    // a delay to allow the animation to finish before dismissing the spinner
    await new Promise(resolve => setTimeout(resolve, 300))
    this.spinner.hide()
  }
```

and finally the animation:
```typescript
import {
    trigger,
    state,
    style,
    animate,
    transition,
  } from '@angular/animations';

export const fadeInAnimation = trigger("fadeIn", [
    state("out", style({
      opacity: 0
    })),
    state("in", style({
      opacity: 1
    })),
    transition("out <=> in", [
      animate(200)
    ])
  ])
```

**Comment by Napster2210** [comment]
@jpike88 @dkruchok @nadav96 This has been done and will be available in next version.

**Comment by Napster2210** [comment]
This is available in version `v8.1.0`

**Comment by jpike88** [comment]
Thanks mate

**Comment by Glamurio** [comment]
Hey I wanted to follow up on this, I can see that there's an animation now, but is there a way to turn off the smooth transition? Or am I better off downgrading to a previous version?

**Comment by rspl-yuvraj** [comment]
@Glamurio Currently there is no way to turn off the animation.

**Comment by Glamurio** [comment]
@rspl-yuvraj Thanks, I'd really like for there to be an option to turn it off in a future version

**Comment by rspl-yuvraj** [comment]
Sure @Glamurio I'll keep in mind
