### ISSUE TITLE
using [Fullscreen]="false" don't work 

### ISSUE THREAD

**Issue by tankejaures** [Napster2210/ngx-spinner#74]
<div class="auth-wrapper d-flex no-block justify-content-center align-items-center">
  <div class="auth-box">
    <ngx-spinner [fullScreen]="false" type="ball-clip-rotate-multiple" size="medium">
      <p class="loading">Loading Awesomeness...</p>
    </ngx-spinner>
 </div>
</div>

auth-box it fix of height=400px;

**Comment by rspl-yuvraj** [comment]
@tankejaures Can you please more details? 
Which version of `ngx-spinner` you're using?
Which version of Angular you're using?
For Reference: https://stackblitz.com/edit/angular-7arfhb

**Comment by Murena7** [comment]
same issue: 
Can't bind to 'fullScreen' since it isn't a known property of 'ngx-spinner'.

Angular 7.2.9
ngx-spinner: 7.1.1

**Comment by tankejaures** [comment]
> @tankejaures Can you please give me more details?
> Which version of `ngx-spinner` you're using?
> Which version of Angular you're using?
> For Reference: https://stackblitz.com/edit/angular-7arfhb

I am usign "ngx-spinner": "^7.1.4" and angular 7.1.4

**Comment by Napster2210** [comment]
@tankejaures @Murena7 Your parent container(div) should have `position: relative;`

**Comment by tankejaures** [comment]
@Napster2210 thank's it work

**Comment by shubh9415** [comment]
@Napster2210 Could you please give an example because I have tried this.
<div style="position: relative">
        <ngx-spinner name="sp1" [fullScreen]="false" type="ball-clip-rotate-multiple" size="medium"></ngx-spinner>  </div>

but still getting the error.
'Can't bind to 'fullScreen' since it isn't a known property of 'ngx-spinner''

**Comment by itniels** [comment]
I also cannot set fullScreen="false" neither in HTML or in the `.show()` method.

**Comment by langebangen** [comment]
I have the same problem too. Whether i set position: relative on a parent div, set fullScreen on the component or with the spinnerservice, still it shows the spinner in full screen.

**Comment by rspl-yuvraj** [comment]
@langebangen Can you please post your block of code here?

**Comment by rspl-yuvraj** [comment]
@shubh9415 @itniels It would be helpful if you guys can create [Stackblitz](https://stackblitz.com/fork/angular).

**Comment by langebangen** [comment]
I got it working now if i wrapped the ngx-spinner in a div. Thanks for the fast response anyhow!

**Comment by ali9itani** [comment]
It worked when I wrapped ngx-spinner with a div that has a relative position property

**Comment by Michael-Ziluck** [comment]
@Napster2210 Why is it that nowhere in the documentation is it listed that the parent component needs to have `position: relative`? That seems like a pretty important detail...
