### ISSUE TITLE
ngx-spinner can't be built.

### ISSUE THREAD

**Issue by qiurenbo** [Napster2210/ngx-spinner#76]
When I run `npm run build:lib` in projects directory. It appeared `BUILD ERROR`:

> BUILD ERROR
> Cannot read property 'type' of null
> TypeError: Cannot read property 'type' of null
>     at D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:21267:31
>     at Array.forEach (<anonymous>)
>     at removeSummaryDuplicates (D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:21266:15)
>     at TemplateParser.tryParseHtml (D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:20683:33)
>     at TemplateParser.tryParse (D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:20675:25)
>     at TemplateParser.parse (D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:20653:31)
>     at AotCompiler._parseTemplate (D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:24160:47)
>     at AotCompiler._createTypeCheckBlock (D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:23907:27)
>     at D:\Web\ngx-spinner-7.0.0\ngx-spinner-7.0.0\node_modules\_@angular_compiler@7.2.13@@angular\compiler\bundles\compiler.umd.js:23875:31
>     at Array.forEach (<anonymous>)

Did I do something wrong?

**Comment by rspl-yuvraj** [comment]
@qiurenbo It would be good if you share package json and some portion of code

**Comment by qiurenbo** [comment]
rspl-yuvraj, thank you for your reply. 

I git clone https://github.com/Napster2210/ngx-spinner.git.  And then I run `npm install` in the ngx-spinner directory. 


I didn't change anything else. But when I run `npm run build:lib`  as mentioned in package.json. I meet this Error.

So the question is when you build the ngx-spinner by running  `npm run build:lib`, everything is ok?

![image](https://user-images.githubusercontent.com/12886911/56173709-69febc00-6021-11e9-97e4-670b0eed846a.png)

**This is content of pakage.json**
```
{
  "name": "ngx-spinner",
  "version": "7.1.4",
  "scripts": {
    "ng": "ng",
    "start": "ng serve ngx-tester -o",
    "build:lib": "ng build ngx-spinner && npm run copy",
    "copy": "cp README.md dist/ngx-spinner/",
    "build:app": "ng build ngx-tester --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^7.2.2",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "ngx-color-picker": "^7.3.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.12.0",
    "@angular-devkit/build-ng-packagr": "~0.12.0",
    "@angular/cli": "~7.2.2",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.34.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

**Comment by qiurenbo** [comment]
I think I know the cause of this problem. I use cnpm ( a package management tool from china) to install the dependencies.  It acts differently from npm. 

Finally, when I change to use npm. Everything is OK,
