### ISSUE TITLE
Remove !important from .black-overlay z-index

### ISSUE THREAD

**Issue by Althain2** [Napster2210/ngx-spinner#77]
Hello,

- The spinner class 'black-overlay' has set !important on z-index property. 
- In my case the spinner is not used in fullscreen mode 
The problem: The spinner's 'black-overlay' is shown over ngx-botstrap modal overlay.
How it should be: In this case the spinner's 'black-overlay' should be hidden behind ngx-botstrap modal overlay.

Suggested solution: 
- Remove !important from z-index .black-overlay, so it can be overwritten by Angular's global CSS rules.
- MOREOVER: if the animations also have !important on z-index, the !important should also be removed from there.

**Comment by rspl-yuvraj** [comment]
@Althain2 Thanx for the suggestion, I'm trying to put `z-index` as a @Input property so user can set whatever value they want.

**Comment by Napster2210** [comment]
@Althain2 This has been resolved and will be available in the next version.

**Comment by Napster2210** [comment]
This is available in version `v8.1.0`
