### ISSUE TITLE
Backdrop Opacity not working

### ISSUE THREAD

**Issue by Mynken** [Napster2210/ngx-spinner#78]
Even on this page https://napster2210.github.io/ngx-spinner/, when changing 
Backdrop Opacity form 0.1 to 1 or 9999 no difference.

**Comment by Napster2210** [comment]
@Mynken It's DEMO issue, I have removed that property long back. Please refer [README](https://github.com/Napster2210/ngx-spinner/blob/master/README.MD)

![image](https://user-images.githubusercontent.com/17761063/56391154-6f3f4f00-624b-11e9-9bd2-20c92c002d19.png)

I'll fix it next release.
