### ISSUE TITLE
not full screen width and heigh for spinner using A7

### ISSUE THREAD

**Issue by rabindranathfv** [Napster2210/ngx-spinner#79]
i wantend to use your spinner with my interceptetor implementation and it works well but the spinner do not get 100% of the width and heigh of viewport...i see the syle in browser and u set with this styles
```
top: 0;
left: 0;
width: 100%;
height: 100%;
z-index: 99999 !important;
```
is good but if you need you make some scroll with spinner is loading you loose viewport, can you use width: 100vw; and height: 100vh; or setting up width and height via input?

really good jobs with this...i am using in production

**Comment by Napster2210** [comment]
Have you tried to set [fullScreen]="true" property?

**Comment by rabindranathfv** [comment]
@Napster2210 yes, but when i do scroll do not get full screen
 ```
<ngx-spinner bdOpacity=0 bdColor="rgba(51,51,51,0.44)" size="large" color="#FFCD00" type="ball-spin-clockwise-fade" [fullScreen]="true">
 
    </ngx-spinner>
```

**Comment by Napster2210** [comment]
Which version of "ngx-spinner" you're using?

**Comment by rabindranathfv** [comment]
"ngx-spinner": "^7.1.1"  with angular 7

**Comment by rabindranathfv** [comment]
Chrone last version - angular v7 - "ngx-spinner": "^7.1.1"
![image](https://user-images.githubusercontent.com/28325503/56755963-ba32f800-675e-11e9-830a-8a0738c4066a.png)

when i inspect apply those styles
```
top: 0;
left: 0;
width: 100%;
height: 100%;
z-index: 99999 !important;
```

**Comment by Napster2210** [comment]
@rabindranathfv There should be some inline properties as well:
```
background-color: rgba(51, 51, 51, 0.8);
position: fixed;
```

**Comment by rabindranathfv** [comment]
@Napster2210 another style is applied
```
background-color: rgba(51, 51, 51, 0.44);
position: absolute;
```
is this for the version right?

**Comment by Napster2210** [comment]
Yes, please

**Comment by rabindranathfv** [comment]
@Napster2210 updated but still not working well and still have the same styles i told U before updated

**Comment by Napster2210** [comment]
Position should be fixed not absolute

**Comment by chrismclellen** [comment]
I'm on `7.1.4` and having the same issue. 

The inline styling is taking precedence and setting to absolute:

```<div _ngcontent-c9="" class="overlay ng-star-inserted" ng-reflect-ng-style="[object Object]" style="background-color: rgba(51, 51, 51, 0.8); position: absolute;">```

For whatever reason, this line is not working right in ngx-spinner.component.html:
`[style.position]="spinner.fullScreen ? 'fixed' : 'absolute'"`

And I second the opinion that this is nicely done. Great job. :)

**Comment by Gixen** [comment]
I'm also on ```7.1.4``` and having the same issue.

**Comment by SuperPanBagna** [comment]
I use the latest version (7.1.4), with Angular 7.

![Captura de pantalla de 2019-04-26 12-10-17](https://user-images.githubusercontent.com/36860565/56823364-a4d2d200-6821-11e9-8e91-948cfce9486e.png)

The "overlay" class contains "position: fixed;". 
But it's not applied because the style attribute in the same div :

 style = "background-color:rgba(51,51,51,0.44); position: absolute;" 

As a temporary solution: I use :: ng-deep to add the !important rule like this :

`
.loader ::ng-deep .overlay{
  position: fixed !important;
}

`

then 

` <ngx-spinner 
class="loader" 
bdOpacity=0
 bdColor="rgba(51,51,51,0.44)" 
size="large"
color="#FFCD00"
type="ball-spin-clockwise-fade"
[fullScreen]="true" >

</ngx-spinner>`

**Comment by rspl-yuvraj** [comment]
@rabindranathfv @SuperPanBagna @Gixen @chrismclellen Marked as a bug I'll look into it and fix will be available in next release.

**Comment by jsebastianch** [comment]
I have the same issue any workaround?

**Comment by chrismclellen** [comment]
@SuperPanBagna's css override worked for me.

**Comment by mersacs** [comment]
i have same issue, 
@SuperPanBagna solution worked for me.

**Comment by tghkuma** [comment]
In this [line](https://github.com/Napster2210/ngx-spinner/blob/master/projects/ngx-spinner/src/lib/ngx-spinner.component.ts#L105), since `spinner.fullScreen` is updated even if undefined, fullScreen is treated as false.

**Comment by FredeHo** [comment]
Custom class on ngx-spinner with "position: fixed !important" (with or without ::ng-deep) didn't work for me. No styles got applied. Even in app.component.scss. Only thing that fixed it, was
```
ngx-spinner {
    .overlay {
        position: fixed !important;
    }
}
```

**Comment by Napster2210** [comment]
@rabindranathfv @chrismclellen @Gixen @SuperPanBagna @jsebastianch @mersacs @tghkuma @FredeHo Can you guys please check the latest version **v8.0.1**?
https://github.com/Napster2210/ngx-spinner/releases/tag/v8.0.1
