### ISSUE TITLE
Spinner doesn't show on ngOnInit as sample suggests

### ISSUE THREAD

**Issue by jamisonroberts** [Napster2210/ngx-spinner#80]
There was an issue closed by the issue creator about two weeks ago (issue 75), however I wonder if there is an issue here after all, either with documentation or with actual implementation.

The spinner will not show if call is in ngOnInit.  Contrary to what worked for the fellow that created issue 75, neither of those solutions work for me either (ngAfterContentChecked or a very short timeout in ngOnInit).

Here's a stackblitz to illustrate:
https://stackblitz.com/edit/angular-afl7eq

**Comment by jschoong970818** [comment]
Same problem here. any solutions out there?

**Comment by jamisonroberts** [comment]
> Same problem here. any solutions out there?

This snippet does seem to work, but it doesn't exactly make me feel good to use it just because I can't be sure that this "fix" would work in all situations.

`setTimeout(() => this.spinner.show(), 25);
`

**Comment by jschoong970818** [comment]
> > Same problem here. any solutions out there?
> 
> This snippet does seem to work, but it doesn't exactly make me feel good to use it just because I can't be sure that this "fix" would work in all situations.
> 
> `setTimeout(() => this.spinner.show(), 25); `
> 
> The above was proposed in issue #75 .

Thanks so much! this works!

**Comment by singhmohancs** [comment]
It is not working for me too. I found an alternate https://github.com/t-ho/ngx-ui-loader

**Comment by rspl-yuvraj** [comment]
@jamisonroberts @jschoong970818 Marked as a bug will be resolved in next release.

**Comment by rspl-yuvraj** [comment]
@jamisonroberts @jschoong970818 For a temporary workaround you can use `ngAfterViewInit` instead of `ngOnInit`.

**Comment by jschoong970818** [comment]
Okie dokie, @rspl-yuvraj thanks a lot!!! that works!

**Comment by pavankjadda** [comment]
I am facing a similar issue. Using workaround for the timebeing

**Comment by TdoubleG** [comment]
@rspl-yuvraj the ngAfterViewInit throws an error:
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: false'. Current value: 'ngIf: true'.
    at viewDebugError (core.js:20440)
    at expressionChangedAfterItHasBeenCheckedError (core.js:20428)
    at checkBindingNoChanges (core.js:20530)
    at checkNoChangesNodeInline (core.js:23401)
    at checkNoChangesNode (core.js:23390)
    at debugCheckNoChangesNode (core.js:23994)
    at debugCheckDirectivesFn (core.js:23922)
    at Object.eval [as updateDirectives] (NgxSpinnerComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:23911)
    at checkNoChangesView (core.js:23289)
```

**Comment by Napster2210** [comment]
@jamisonroberts @jschoong970818 @pavankjadda @TdoubleG Can you guys please check the latest version **v8.0.1**?
https://github.com/Napster2210/ngx-spinner/releases/tag/v8.0.1
