### ISSUE TITLE
Relax peer dependency for angular/core v8

### ISSUE THREAD

**Issue by jpike88** [Napster2210/ngx-spinner#81]
Angular/core@8.0.0-rc-0 is out, would be good if this is tested and the peer dependency requirement relaxed.

**Comment by Napster2210** [comment]
@jpike88 Sure will release a new version `8.0.0` with all update dependencies and some new exciting new features as well

**Comment by elimin8r** [comment]
@Napster2210 any update on this?

**Comment by Napster2210** [comment]
@elimin8r I'll release new version in a week.

**Comment by jbonet** [comment]
How is this going

**Comment by Napster2210** [comment]
@jbonet I need two more days for that due to busy schedule.

**Comment by Napster2210** [comment]
@jpike88 @elimin8r @jbonet Please check latest version **v8.0.1**

**Comment by elimin8r** [comment]
maybe im doing it wrong, but...
```
npm WARN ngx-spinner@8.0.1 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@8.0.1 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by Devfdez** [comment]
@elimin8r I had these issues too but after upgrading to 8.0.3 the warnings resolved.
