### ISSUE TITLE
Spinner spins forever if ChangeDetectionStrategy is OnPush

### ISSUE THREAD

**Issue by holger-at-schottel-de** [Napster2210/ngx-spinner#82]
Spinner spins forever if `ChangeDetectionStrategy` of a component is `OnPush`.

I addition to my [pull request](https://github.com/Napster2210/ngx-spinner/pull/68) I now provide a "real life" example (without using setTimeout) making a http request to a fake backend: 
https://stackblitz.com/edit/ngx-spinner-change-detection-onpush

To see the problem just switch `changeDetection` in `AppComponent` between `OnPush` and `Default`.

**Comment by abnerey** [comment]
I'm not pretty sure about your issue, but probably it resides on the way you disable the spinner; if you are disabling it from a function which it's only called through the change detection system, that's definitely the problem. You can try putting a console.log on that place/function/whatever and see the console, if it's logging something, there is an issue with ngx-spinner, but if it isn't, there is an issue with your code and/or the way you do the things inside your component.

**Comment by holger-at-schottel-de** [comment]
There are already console.logs in the code. Just have a look at it and you will see that the `show` and `hide` methods of `NgxSpinnerService` are called. Even though the `hide` method is called, the spinner does not get hidden.

**Comment by abnerey** [comment]
Right, well, I can't test it right now, but I suspect about the ChangeDetectionStrategy.OnPush which the app.component has. Have you tried use hide on a lower component? (Using onpush)

**Comment by abnerey** [comment]
Btw, I've made a library like ngx-spinner, it's called busyness and it does the thing you wanna do out-of-the-box (block on requests)

**Comment by holger-at-schottel-de** [comment]
> Right, well, I can't test it right now, but I suspect about the ChangeDetectionStrategy.OnPush which the app.component has. Have you tried use hide on a lower component? Using onpush on it and removing onpush from the app.component. Putting onpush on the root component practicely disable the change detection on the entire tree of components, because it works just for Input based components, it's not a good strategy using it on the highest component

`NgxSpinnerService` is not called from within the app.component, but it's called from the http interceptor. The app.component just contains the `ngx-spinner` component.

**Comment by holger-at-schottel-de** [comment]
> Btw, I've made a library like ngx-spinner, it's called busyness and it does the thing you wanna do out-of-the-box (block on requests)

Thanks for the hint, I will have a look into it.

**Comment by Napster2210** [comment]
@holger-at-schottel-de @abnerey Can you guys please check the latest version **v8.0.1**?
https://github.com/Napster2210/ngx-spinner/releases/tag/v8.0.1
Feel free to create a new issue if you still face the same issue.

**Comment by holger-at-schottel-de** [comment]
Hi @Napster2210,
after upgrading the StackBlitz project to ngx-spinner version 8.0.1 and angular 8.1.1 it's working fine. I cannot check with our applications, because we are still on angular 7.2.x. I will check again after upgrading angular to version 8 or the issue https://github.com/Napster2210/ngx-spinner/issues/89 has been fixed.

Thanks for you work!

**Comment by Napster2210** [comment]
Thanx for supporting and using the package. @holger-at-schottel-de
