### ISSUE TITLE
spinner is not visible

### ISSUE THREAD

**Issue by himanshu2521992** [Napster2210/ngx-spinner#83]
spinner is not showing when using in feature module. Had to roll back to 7.0.0, then it worked

**Comment by Napster2210** [comment]
@himanshu2521992 Can you post a demo using [Stackblitz](https://stackblitz.com/)

**Comment by himanshu2521992** [comment]
Hi,
I am new to stackblitz, so i tried creating an app, but unable to show spinner.
https://stackblitz.com/edit/angular-n9fmxx
check the code, make it work then I'll show you the actual problem

**Comment by himanshu2521992** [comment]
https://stackblitz.com/edit/angular-n9fmxx
check here I tried to use it in test component and installed version is     "ngx-spinner": "^7.1.4",
and spinner is not visible when i am installing v.7.0.0 it is working properly. Why?

**Comment by fthiemonge** [comment]
I had a similar issue where it worked the first time (show() then hide()) but not on subsequent show() calls after that first hide() call. Downgrading worked for me as well. Tracing through the code I found in the 7.1.4 version that the "fullScreen" property was undefined the second time around though it was "true" the first time, so I believe that's getting unset somehow, perhaps in the "hide" call? That may or may not be the issue. Hope this helps.

**Comment by danieldanielecki** [comment]
+1, had the same issue on 7.1.4, downgrading to 7.0.0 fixed the problem.

**Comment by himanshu2521992** [comment]
@Napster2210 See all are facing the same issue, and as I said, on downgrading its working properly.

**Comment by Napster2210** [comment]
@himanshu2521992 @danieldanielecki @fthiemonge Working on this issue will release with Angular v8 in a week.

**Comment by Napster2210** [comment]
@himanshu2521992 @fthiemonge @danieldanielecki Can you guys please check latest version **v8.0.1**.
Feel free to create a new issue if you still face the same issue.

**Comment by mslosarek** [comment]
This is still in issue in `"ngx-spinner": "^7.2.0"` and the version 8 of the library doesn't work with Angular 7

**Comment by Napster2210** [comment]
@mslosarek Can please check version of `ngx-spinner` in lock file? And what's your Angular version?
