### ISSUE TITLE
cannot bind with name

### ISSUE THREAD

**Issue by sagius-li** [Napster2210/ngx-spinner#84]
in case of multiple spinners, i can assign a constant name to the spinner like
`<ngx-spinner name="sp1">`
and then show the spinner using show('sp1'). it works fine

but i cannot use data binding. i've tried,
`<ngx-spinner [name]="value">`
`<ngx-spinner name="{{value}}">`
`<ngx-spinner [attr.name]="value">`
none of them works. the first two even throw compile errors

**Comment by TdoubleG** [comment]
Hey @Napster2210 do you know when there will be a fix for this one?

**Comment by Napster2210** [comment]
@TdoubleG In next few days I'll release new version v8, in that it'll be resolved

**Comment by TdoubleG** [comment]
Hey @Napster2210 is the fix already in the v8 branch? I really need it :)

**Comment by rspl-yuvraj** [comment]
@TdoubleG Working on it will release this week.

**Comment by TdoubleG** [comment]
Hey @rspl-yuvraj  maybe this week :D?

**Comment by Napster2210** [comment]
@TdoubleG This week :stuck_out_tongue_winking_eye:

**Comment by Napster2210** [comment]
@sagius-li @TdoubleG Can you guys please check latest version **v8.0.1**.
Feel free to create a new issue if you still face the same issue.

**Comment by flowest** [comment]
could this fix be added in a v7.* version, since v8.* doesnt work with an angular 7 app?

**Comment by shan75** [comment]
Hi
I am using the latest version ie "ngx-spinner": "^8.0.3"
I have one new issue. I am binding the name using a variable. It seems to work fine. But I am loading multiple spinners to add one spinner in a row. For example there are five rows when page loads, the spinners are working in all five rows. But there will be add button which adds a new row , I can see the spinner is added to the dom but the newly created spinner is not working even though it got the correct name.  May I know how to resolve it?

**Comment by rspl-yuvraj** [comment]
@shan75 Can you try with different `changeDetectionStrategy` may `onPush`?

**Comment by shan75** [comment]
Hi

Thanks for getting back, but it doesn't seem to have any impact. I will setup online example and send it to you so easy to look at

Thanks
________________________________

**Comment by shan75** [comment]
Hi

I have resolved this. We don't really need changeDetectionStrategy , it works even without that.

Regards
Shan
________________________________

**Comment by WiharlleyWill** [comment]
I had same problem, I fixed with:

`<ngx-spinner [name]="'name'">`

Working fine 👍
