### ISSUE TITLE
Update to angular 8

### ISSUE THREAD

**Issue by jpike88** [Napster2210/ngx-spinner#85]
```ngx-spinner@7.1.4 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@7.1.4 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by jpike88** [comment]
@Napster2210 I've been using angular 8 since the first beta, this works fine on it

**Comment by jpike88** [comment]
@Napster41 is anyone getting this??

**Comment by jpike88** [comment]
@Napster2210 @rspl-yuvraj is this going to be sorted eventually??

**Comment by jpike88** [comment]
Screw it... I'll use my own implementation

**Comment by lonix1** [comment]
@jpike88 Please reopen, update to 8 still needs to be done...

**Comment by jpike88** [comment]
Maintainer is dead or stopped caring. I advise you fire up a matprogress and cdkoverlay instead and avoid this library
