### ISSUE TITLE
Please upgrade to Angular 8

### ISSUE THREAD

**Issue by lonix1** [Napster2210/ngx-spinner#86]

**Comment by rspl-yuvraj** [comment]
@lonix1 This week I'll release v8 with some major fixes and features.

**Comment by TonyAdamo** [comment]
Hi @rspl-yuvraj, any update on this?

**Comment by Napster2210** [comment]
@TonyAdamo I was busy in my regular stuff but I'll try my best to deliver in this week.

**Comment by lonix1** [comment]
I also hate the "regular stuff" :rage: 
I wish I could be here all the time, but that's life... :smiley:

**Comment by Napster2210** [comment]
@lonix1 @TonyAdamo It's done, check it out latest version **v8.0.1**.
