### ISSUE TITLE
Subscribe to spinner state in ngx-spinner 7.x.x

### ISSUE THREAD

**Issue by akash-potdar7** [Napster2210/ngx-spinner#87]
Angular 8.x
ngx-spinner 7.1.4

previously I used ngx-spinner 2
and I used to do this to subscribe to the state of the spinner `this.spinner.spinnerObservable.subscribe(state => {`
`      this.isLoading = state;`
 `});`

This worked since spinnerObservable wasn't a private variable.
But in new version of ngx-spinner(7.1.4) this is a private variable.

Question is what is the new/ updated view of subscribing to the spinner state?

**Comment by Napster2210** [comment]
@akash-potdar7 Why do you need state of spinner? Can you please let me know about your scenario?

**Comment by Napster2210** [comment]
No response after long time, closing the issue.
