### ISSUE TITLE
Typo in fesm5/ngx-spinner.js

### ISSUE THREAD

**Issue by TdoubleG** [Napster2210/ngx-spinner#89]
Currently there is a Warning which causes an error at the frontend:

WARNING in ./node_modules/ngx-spinner/fesm5/ngx-spinner.js 208:59-77
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

Removing the 'ee' manually fixes the problem, but this won't work with CI.

**Comment by TdoubleG** [comment]
Seems to be a problem with Angular < 8.0. Used the spinner in Angular 7 and 8

**Comment by Napster2210** [comment]
@TdoubleG Maybe because I'm not facing issue with Angular 8+

**Comment by TdoubleG** [comment]
Think so. But currently the Spinner is not usable for Angular 7 in an CI environment. Will there be a solution`?  Otherwise you need to update the readme that it's only for Angular 8+

**Comment by Napster2210** [comment]
@TdoubleG I'll check with Angular 7 again if it's still not working properly I'll release separate version from Angular 7. But they should provide backward compatibility with Angular 8.

**Comment by TdoubleG** [comment]
@Napster2210 Alright thank you :)

**Comment by tundet** [comment]
Experiencing the exact same issue with Angular 6.

**Comment by Bhavin3184** [comment]
Experiencing the exact same issue with Angular 7.

**Comment by Napster2210** [comment]
@TdoubleG @tundet @Bhavin3184 I'll release new version by today which includes fixes for the same.

**Comment by Bhavin3184** [comment]
You are the life saver.....

Regards,
Bhavin Jadav.

**Comment by Napster2210** [comment]
@TdoubleG @tundet @Bhavin3184 I have checked the issue in detail, I come up with that it's due to Angular v8.
https://angular.io/api/core/defineInjectable
They have deprecated `defineInjectable` in v8 and replaced it with `ɵɵdefineInjectable` in compiled code. But that is not available in older version like Angular v6 and v7. That is the reason you guys are getting error with older version.

**Comment by Napster2210** [comment]
@TdoubleG @tundet @Bhavin3184 I have release two different versions:
For Angular 6/7: `7.2.0`
For Angular 8: `8.0.3`

**Comment by TdoubleG** [comment]
@Napster2210 works buddy, thank you :)

**Comment by pragadeesh26** [comment]
I am using angular 7 but the ngx spinner 7.2.0 is not working for me..

**Comment by Bhavin3184** [comment]
What error you getting?
    On ‎Thursday‎, ‎13‎ ‎February‎ ‎2020‎ ‎03‎:‎51‎:‎26‎ ‎PM‎ ‎AEDT, pragadeesh26 <notifications@github.com> wrote:  
 
 
I am using angular 7 but the ngx spinner 7.2.0 is not working for me..
