### ISSUE TITLE
Dependency error when installing on Angular 5.2.9

### ISSUE THREAD

**Issue by jffribeiro** [Napster2210/ngx-spinner#9]
Hello,

The ngx-spinner version 1.1.0 should work on Angular 5.2.9 ?

$>npm install ngx-spinner@latest --save
npm WARN ngx-spinner@1.1.0 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.

"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
...

Tks!
Jorge

**Comment by Napster2210** [comment]
@jffribeiro Currently I'm working on the v4 related issue, will release another version with the latest version of Angular as soon as possible.

**Comment by jffribeiro** [comment]
Tks, @Napster2210!

**Comment by Napster2210** [comment]
@jffribeiro Can you please check again the same with the latest version(**v2.0.0**)?
