### ISSUE TITLE
Two instances of MyComponent with spinner

### ISSUE THREAD

**Issue by roma2341** [Napster2210/ngx-spinner#90]
My main template looks like:
```
<myComponent></myComponent>
<myComponent></myComponent>
```
MyComponent template:
` <ngx-spinner name="spinner1"> </ngx-spinner>`

I want to show spinner with name "spinner1". But spinners are showed in both components (because names are same due to components are same) and i have to randomize spinners names to prevent such behaviour;

**Comment by Napster2210** [comment]
Use @Input for your `myComponent` and pass the different name for spinner and use that name(your @Input property) as `[name]` in `ngx-spinner`

**Comment by Napster2210** [comment]
```
<myComponent spinnerName="spinner1"></myComponent>
<myComponent spinnerName="spinner2"></myComponent>

<ngx-spinner [name]="spinnerName"><ngx-spinner>
```

**Comment by KishanIos007** [comment]
what if I don't want to put HTML in my component and wanted to manage through service only. Just curious

**Comment by rspl-yuvraj** [comment]
@KishanIos007 In that case, you can change options using service.
https://stackblitz.com/edit/angular-exgxk2

**Comment by KishanIos007** [comment]
Great Thanks man !

**Comment by Napster2210** [comment]
Closing the issue due to inactivity.
