### ISSUE TITLE
ngx-spinner not loading in lazy loaded components

### ISSUE THREAD

**Issue by kiranhpe** [Napster2210/ngx-spinner#92]
ngx-spinner loads fine in eagerly loaded components but not loading in lazy loaded components.

**In this case "User Component" were lazy loaded**

**app.module.ts**
![Capture](https://user-images.githubusercontent.com/22594383/61039256-0996d500-a3ec-11e9-9e38-b9cef6f0b72b.PNG)

**user.component**
![Capture1](https://user-images.githubusercontent.com/22594383/61039385-4367db80-a3ec-11e9-83e8-f931b9b6e91a.PNG)
![Capture2](https://user-images.githubusercontent.com/22594383/61039411-51b5f780-a3ec-11e9-8500-7def8d15a73f.PNG)

**Error Message**
![Capture3](https://user-images.githubusercontent.com/22594383/61039488-7ad68800-a3ec-11e9-8de9-bfafc72ac64e.PNG)

**Comment by Napster2210** [comment]
@kiranhpe You've to import `CUSTOM_ELEMENTS_SCHEMA` in AppModule as `ngx-spinner` is custom element.

**Comment by kiranhpe** [comment]
@Napster2210 even after importing to AppModule getting the same error.
![Capture4](https://user-images.githubusercontent.com/22594383/61040664-a78b9f00-a3ee-11e9-9841-2dfc6cfc22b3.PNG)
![Captur5](https://user-images.githubusercontent.com/22594383/61040714-c0945000-a3ee-11e9-8b95-c3d83a94aa8b.PNG)

**Comment by Napster2210** [comment]
@kiranhpe Try to import in the module which contains your User component once and check it again.

**Comment by kiranhpe** [comment]
@Napster2210 Thanks mate.. It's working now
