### ISSUE TITLE
ERROR Error: "Uncaught (in promise): TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by christianbaw** [Napster2210/ngx-spinner#96]
I'm having this error when i try to use ngx-spinner. I'm currently using angular 7.3.8, I saw in other posts that firebase could be an issue but I'm not using it, anyone can point me in the right direction ?

**Comment by Napster2210** [comment]
@christianbaw Which version of `ngx-spinner`, you're using?

**Comment by christianbaw** [comment]
@Napster2210 according to my package.json I'm using the latest version which it would be 8.0.3

**Comment by Napster2210** [comment]
@christianbaw for Angular 7 you've to use version `7.2.0`

**Comment by Napster2210** [comment]
https://github.com/Napster2210/ngx-spinner/blob/master/README.MD#whats-new

**Comment by christianbaw** [comment]
@Napster2210 well that was awkward lol, sorry for not reading, is now working, thank you!!
