### ISSUE TITLE
Targetting to run within a dv

### ISSUE THREAD

**Issue by shan75** [Napster2210/ngx-spinner#98]
Hi I am trying to use this and it is a very nice piece of work.  But I am trying to target to run within a small div.  It doesn't matter where I place the component, it runs for a whole div. Can't figure out how to do it.

For example, i want this to run within div with id="spinnerarea"  How to do it?

Thanks

**Comment by Napster2210** [comment]
@shan75 Check this out: https://stackblitz.com/edit/angular-7arfhb
Let me know if you want anything else.

**Comment by shan75** [comment]
Hi

Thanks for getting back.  I have seen this demo. But it is not working for me.

In my case,

 <div id="Area">
        <div class="center">
            <div id="spinarea">
                   
            </div>
            <p class="loadingText">Loading STL Preview...</p>
        </div>
    </div>


Not sure whether I am making it clear

Thanks
Shan

________________________________

**Comment by shan75** [comment]
Hi

Even in your own demo,  I want to show spinner either in the header or just in the footer. Please refer below.  How do I achieve it?

<nb-layout center>
  <nb-layout-header>
  <ngx-spinner [fullScreen]="false" type="ball-clip-rotate-multiple" size="medium">
          <p class="loading">Loading Awesomeness...</p>
        </ngx-spinner>

  </nb-layout-header>

  <nb-layout-column>
    <p>This is a demo of the spinner which displays in below card with loading text, it'll hide after 5 seconds automatically.</p>


    <button nbButton status="success" (click)="showSpinner()">Start Spinner</button>
  </nb-layout-column>

  <nb-layout-footer>

  <ngx-spinner [fullScreen]="false" type="ball-clip-rotate-multiple" size="medium">
          <p class="loading">Loading Awesomeness...</p>
        </ngx-spinner>
Footer
  </nb-layout-footer>
</nb-layout>

________________________________

**Comment by Napster2210** [comment]
Can you create a stackblitz demo? So I can help you in a better way.

**Comment by shan75** [comment]
Hi Yuvraj

Just in your own example demo,   hwo do I make the spinner to display only in header?

That is my question

Thanks
Shan

________________________________

**Comment by Napster2210** [comment]
Okay let me try give me few minutes.

**Comment by Napster2210** [comment]
@shan75 Got the solution, make sure you've set `position: relative` in your parent element.

**Comment by shan75** [comment]
Hi

I got it. Thank you very much

Shan
________________________________
