### ISSUE TITLE
[Question] Wrap component

### ISSUE THREAD

**Issue by lonix1** [Napster2210/ngx-spinner#99]
I'm still new to Angular so please forgive the newbie question.

I use this spinner everywhere:
````html
<ngx-spinner
  bdColor="rgba(51, 51, 51, 0.5)"
  size="medium"
  color="#fff"
  type="ball-beat"
>
  <p style="font-size: 20px; color: white">Loading...</p>
</ngx-spinner>
````

It would be neater/simpler to do this instead:
````html
<myspinner></myspinner>
````

Does someone know how to wrap it like this?

**Comment by BobNudd** [comment]
You'd ideally pass a configuration at the Module import, but this isn't supported. This would be fantastic especially for an interceptor implementation.

I personally control spinner through my components, and pass a static config depending upon the requirements of the spinner.

Example:

In component:

`this.spinnerService.show('user-edit-personal', SpinnerConfig.mediumBox());`

```
export class SpinnerConfig {

    public static mediumBox() {
       const getConfig: Spinner = {
            type: 'ball-clip-rotate-multiple',
            fullScreen: false,
            size: 'large',
            bdColor: 'rgba(255,255,255,1)',
            color: 'rgba(237, 133, 56, 0.8)',

        };

        return getConfig;
    }
```

Then including the component in your template is quite clean:

`<ngx-spinner name="user-edit-personal"></ngx-spinner>`

**Comment by rspl-yuvraj** [comment]
@lonix1 You can do like this:

```
// Create separate component
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'custom-app',
  template: '<ngx-spinner></ngx-spinner>'
})
export class MyComponent{}

// In your HTML
<custom-app></custom-app>

// Import the same component in the module as well
...
import { MyComponent } from "./my.component";
...
declarations: [..., MyComponent],
...
```
